### ISSUE TITLE
Corretto 11 with OpenJFX

### ISSUE THREAD

**Issue by yamadamn** [corretto/corretto-11#1]
This issue is just a question for now.

I have tried Corretto 8 and it includes JavaFX(OpenJFX).
https://stackoverflow.com/questions/53375201/is-javafx-supported-by-corretto

But, when I try to use Corretto 11, I noticed it doesn't include OpenJFX.
Is it by design? 

### Platform information
    OS: Windows 10
    Version:
    openjdk version "11.0.2" 2019-01-15 LTS
    OpenJDK Runtime Environment Corretto-11.0.2.9.1 (build 11.0.2+9-LTS)
    OpenJDK 64-Bit Server VM Corretto-11.0.2.9.1 (build 11.0.2+9-LTS, mixed mode)

P.S. If Corretto 11 doesn't include OpenJFX, I can use other distributions with OpenJFX like Azul ZuluFX or Bellsoft Liberica JDK.
https://www.azul.com/downloads/zulu/zulufx/
https://www.bell-sw.com/java.html

**Comment by davecurrie** [comment]
Hi @yamadamn Corretto 11 doesn't include JavaFX by design. We recommend that you either build your own or use a ready-made distribution such as the ones you link if it fits your needs.

**Comment by agarsan1992** [comment]
Hi,
Is Corretto 11 is compatible with OpenJavaFx? If yes the which version because it's giving error with OpenFx11 and for Corretto 8 it's working fine.

**Comment by rdiez** [comment]
The JDK from BellSoft Liberica does include the JavaFX in their version 11. Check it out here:

https://bell-sw.com/pages/java-11.0.5/

There is even a Chocolatey package for easy installation and upgrade:

https://chocolatey.org/packages/liberica11jdk

I just started a Java 8 application that uses JavaFX 8, and it works fine on the newer 11 version.

Bundling the JavaFX library helps reduce the pain.
