### ISSUE TITLE
The 11.0.7.10.1 x64 Windows Installer does not set file association for jar files

### ISSUE THREAD

**Issue by rj-gp** [corretto/corretto-11#100]
Thank you for taking the time to help improve OpenJDK and Corretto 11.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 11
and is not specific to Corretto 11
we ask that you raise it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system](https://bugs.openjdk.java.net/) or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or [update project](http://mail.openjdk.java.net/mailman/listinfo/jdk-updates-dev).

If your issue is specific to Corretto 11,
then you are in the right place.
Please proceed with the following.

### Describe the bug
jar files are no longer "runnable"  by "opening" in windows after Installing 11.0.7.10.1 x64 JDK.
This is not an issue with 11.0.6.10.1 x64.

### To Reproduce
Download and install amazon-corrretto-11.0.7.10.1-windows.x64.msi.
Try to "run" jar file.

### Platform information
    OS: Windows 10
    Version : 1909 Build 18363.778

C:\Users\randy>java -version
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)

C:\Users\randy>

**Comment by davecurrie** [comment]
Thanks @rj-gp, we're looking at it.

**Comment by ziyiluo** [comment]
Thanks for reporting the issue. Looks like the fix for #21 was accidentally reverted.

**Comment by lutkerd** [comment]
This was resolved in the packaging logic
