### ISSUE TITLE
half-closed SSLEngine status may cause application dead loop

### ISSUE THREAD

**Issue by bgodbgg** [corretto/corretto-11#103]
#Describe the bug
I will be honest that I am not entirely familiar with the bug, but it seems to have been fixed in the 11.0.8 version of openjdk and I was wondering if you were going to add this to coretto since from everything I can find, coretto is built on 11.0.7?  
https://bugs.openjdk.java.net/browse/JDK-8241054

There are some potential temp fixes from stackoverflow but I was hoping this would be added directly to coretto as I am experiencing the exact problem using coretto11.

https://stackoverflow.com/questions/54485755/java-11-httpclient-leads-to-endless-ssl-loop

**Comment by davecurrie** [comment]
Thanks for getting in touch. OpenJDK 11.0.8 is scheduled for release on 7/14 and Corretto 11.0.8 will be released on the same day. The bugfix will be available then.

Did the workaround of disabling TLS 1.3 work for you as described on the StackOverflow post?

**Comment by bgodbgg** [comment]
Oh perfect - and yes, editing the java.security file in conf to remove TLS 1.3 did work.

**Comment by treacher** [comment]
Hi there, this bug still seems to be present in the latest version of Corretto 11 (11.0.8).

When using this version with TLS 1.3 enabled I'm getting the following error when trying to use a certificate provided by the following root CA: `Entrust Certification Authority - L1M`

```
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

When TLS 1.3 is disabled I no longer get this issue, however this is not a desired long term solution.

**Comment by lutkerd** [comment]
Thanks for letting us know this is still an issue. We will investigate and update you.

**Comment by lutkerd** [comment]
@treacher Can you provide a simple repro case? I was not able to get the same error on my machine or with the openjdk:11.0.8 docker image.
