### ISSUE TITLE
Document specific version download URL structure

### ISSUE THREAD

**Issue by jakauppila** [corretto/corretto-11#112]
### Is your feature request related to a problem?
The [Corretto download page](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html) specifies the URL format when downloading the latest major version.

```
https://corretto.aws/[latest/latest_checksum]/amazon-corretto-[corretto_version]-[cpu_arch]-[os]-[package_type].[file_extension]
```

What is the URL structure when downloading a specific version?

Looking at the following example:

`https://corretto.aws/downloads/resources/11.0.7.10.1/amazon-corretto-11.0.7.10.1-linux-x64.tar.gz`

I would guess it could be:

```
https://corretto.aws/downloads/resources/[corretto_version]/amazon-corretto-[corretto_version]-[os]-[cpu_arch].[file_extension]
```

Is this correct?

Compared to the `latest` format, it doesn't specify the `package_type`, `macos` is instead `macosx`, and Amazon Linux 2 is not distributed that way.

### Describe a solution you would like
Provide clear documentation on URL structure when downloading a specific version of Corretto

**Comment by benty-amzn** [comment]
Thanks for contacting us with this issue. We're looking into this.

While the format for the latest versions are guaranteed, historical artifact naming scheme may vary. We will try to document this for a future release.

**Comment by jakauppila** [comment]
Another question on the topic:
- For the latest releases, a checksum is published to **https://corretto.aws/latest_checksum/package**; is the same done for specific versions? If not, could it be added?

**Comment by AzeemJiva** [comment]
We recommend that customers upgrade to the latest version of Corretto on a regular basis, but understand that there might be use cases that require an older version.  A list of older releases is available in the GitHub releases section here: https://github.com/corretto/corretto-11/releases along with MD5sums.  

Can you explain what you want to accomplish and we can help you solve the problem.

**Comment by jakauppila** [comment]
@AzeemJiva I agree that staying up-to-date on versions is important, but we want to do so in a controlled, orchestrated manner.

So say, within our Chef cookbooks, we will target particular versions that we will periodically update rather than simply pulling down the `latest` version 11 when it executes as we wouldn't want an update to occur in Prod before getting vetted in lower environments first.

**Comment by benty-amzn** [comment]
Structured download information is now available from [corretto/corretto-downloads](https://github.com/corretto/corretto-downloads)
