### ISSUE TITLE
TreeBinAssert.java test failure on Coretto JDK11

### ISSUE THREAD

**Issue by adamfarley** [corretto/corretto-11#117]
### Describe the bug
TreeBinAssert.java test failure on Coretto JDK11.

Details can be found here: https://trss.adoptopenjdk.net/output/test?id=5efea4b42e55416417c06c11

This is a Coretto bug because there is a [fix in the upstream JDK11 repo](https://bugs.openjdk.java.net/browse/JDK-8240655), but it does not appear to have been merged into the Coretto source yet.

Given the age of this change (2-3 months), this appears to indicate some form of bug in the Coretto merge system, assuming there is such a thing.

Thoughts?

### To Reproduce
Run the "java/util/HashMap/TreeBinAssert.java" jtreg test against Coretto JDK11 on Linux x64.

### Expected behavior
The test is expected to pass.

### Platform information
    OS: Linux 64bit
    Version: 11.0.7+10

### Additional context
This issue was raised as to address this one: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1866

If anyone wants to discuss this in near-real-time, I can be found on AdoptOpenJDK's slack channels most workdays.

**Comment by alvdavi** [comment]
Hi, thanks for the heads up.

The fix was merged into jdk11u in April this year, and it is scheduled for 11.0.8. Our master and develop branches are still based on 11.0.7, but after 11.0.8 releases, they will be updated (and this error will be fixed)

**Comment by phohensee** [comment]
11.0.8 is due to GA on July 14, 2020.

**Comment by adamfarley** [comment]
Thanks to both of you. Will close.
