### ISSUE TITLE
Feature Request: Provide SHA256 checksums

### ISSUE THREAD

**Issue by duncaan** [corretto/corretto-11#125]
### Is your feature request related to a problem?
There are no secure checksums provided for the Corretto packages.

### Describe a solution you would like
SHA256 checksums seem to be a standard among software providers.

### Describe alternatives you have considered
While MD5 sums work for now, I'd trust the contents more if they had a more secure checksum.

**Comment by benty-amzn** [comment]
Thanks for contacting us about this.

Providing additional or alternative checksums is something that has been discussed, and they will likely be available for a future release.

If a specific checksum would be helpful for you, please let us know and we'll take that into consideration

**Comment by duncaan** [comment]
SHA256 would be my preference.  Thank you!

**Comment by lutkerd** [comment]
Sha256 hashes are available for the latest releases on the Github release pages and on the Corretto.aws pages  ie: https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html

We do not plan to backfill the hashes, but they will always exist going forward.
