### ISSUE TITLE
Using Amazon Runtime Environment Corretto-11.0.8.10.1 in Linux machine where jdk.internal.misc.Unsafe.park(java.base@11.0.8/Native Method) is consuming 71% thread in application server

### ISSUE THREAD

**Issue by syadav841** [corretto/corretto-11#139]
We are using Using Amazon Runtime Environment Corretto-11.0.8.10.1 in Linux machine where jdk.internal.misc.Unsafe.park(java.base@11.0.8/Native Method) is consuming 71% tread in application servers, wanted to know for what purpose this Method runs

**Comment by alvdavi** [comment]
Hi,

Would you be able to provide us with a full stacktrace. With that, we may be able to understand what is causing this issue.
