### ISSUE TITLE
German button label still announcing 11 RC

### ISSUE THREAD

**Issue by bardware** [corretto/corretto-11#14]
Hi,

on German langauge page https://aws.amazon.com/de/corretto/ the button says `Amazon Corretto 11 RC herunterladen` but eventually leads to the english language download page that offers the final builds.

Thanks for publishing version 11,
Bernhard

**Comment by EricEdens** [comment]
Thanks for reporting. The German localization takes a bit of time to catch up, which is something that we've been thinking about and trying to improve.

I've checked the site and it's updated now.
