### ISSUE TITLE
Enable USDT probes to allow for eBPF tracing

### ISSUE THREAD

**Issue by siwyd** [corretto/corretto-11#142]
In order to be able to perform eBPF tracing on applications running on Amazon Corretto, it seems USDT probes should be enabled. This seems very similar to a feature request on the AdoptOpenJDK build: https://github.com/AdoptOpenJDK/openjdk-build/issues/1173

**Comment by jguo11** [comment]
@siwyd Thank you for the feature request. We will review it and get back to you.
