### ISSUE TITLE
Packaging of 11.0.9 Corretto distribution causing downstream package managers to break

### ISSUE THREAD

**Issue by marc0der** [corretto/corretto-11#145]
### Describe the bug

The current version 11.0.9 has some inconsistencies in it's packaging. This is causing problems in package managers like SDKMAN:
https://github.com/sdkman/sdkman-cli/issues/812

Standard practice for Java related SDKs including the JDK itself is to have only one single directory inside it's tarball distribution. That in turn will contain various artifacts and folders (including `bin`, `lib`, `conf`). This convention is in place to help third parties automate installation of these packages into a single directory.

The latest corretto release has some files in the root folder of the tarball package that looks something like this:

```
├── ADDITIONAL_LICENSE_INFO
├── amazon-corretto-11.0.9.11.1-linux-x64
│   ├── bin
│   │   ├── java
│   │   ├── javac
<snip>
│   ├── conf
│   │   ├── logging.properties
<snip>
├── ASSEMBLY_EXCEPTION
├── LICENSE
├── README.md
└── version.txt
```
The expected form of this package should be something as follows to comply with all other packages and facilitate exploding the sdk:
```
├── amazon-corretto-11.0.9.11.1-linux-x64
│   ├── bin
│   │   ├── java
│   │   ├── javac
<snip>
│   ├── conf
│   │   ├── logging.properties
<snip>
```

### To Reproduce
Extract the package in a local folder and see `ADDITIONAL_LICENSE_INFO`, `ASSEMBLY_EXCEPTION`, `LICENSE`, `README.md`, `version.txt` appear in the current folder.

### Expected behavior
Extracting the current folder should result in only a single folder appearing:
```
amazon-corretto-11.0.9.11.1-linux-x64
```

### Platform information
    OS: Linux
    Version: 11.0.9

### Additional context
This is causing an issue on downstream package managers like SDKMAN, that rely on a sane and consistent binary structure to function properly. No artifacts should live in the root folder of an SDK package.

**Comment by ikysil** [comment]
It looks like only Linux tar.gz packages are affected.

Also, amazon-corretto-11.0.8.10.1-linux-x64.tar.gz is fine.

So the change happened between 11.0.8 and 11.0.9 releases.

**Comment by ikysil** [comment]
There was a recent change in the universal tar.gz packaging script, check

https://github.com/corretto/corretto-11/blame/develop/installers/linux/universal/tar/build.gradle#L134

**Comment by davecurrie** [comment]
Thanks for the feedback, we are working on a fix now.

**Comment by ziyiluo** [comment]
@ikysil thanks for digging into this. You are right, that line change is the culprit. This affects all Linux TGZs except Alpine. We are fixing the packaging at this moment.

**Comment by cliveverghese** [comment]
We have updated the tar.gz packages. The new links are

|Platform   |Type   |Download Link  |Checksum (MD5) |Sig File   |
|---    |---    |---    |---    |---    |
|[Linux x64](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/generic-linux-install.html) |JDK    |[amazon-corretto-11.0.9.11.1-linux-x64.tar.gz](https://corretto.aws/downloads/resources/11.0.9.11.1-1/amazon-corretto-11.0.9.11.1-linux-x64.tar.gz) | `aecee89c6817a26c74587c69cc5c2967` | [Download](https://corretto.aws/downloads/resources/11.0.9.11.1-1/amazon-corretto-11.0.9.11.1-linux-x64.tar.gz.sig) |
|[Linux x86](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/generic-linux-install.html) |JDK    |[amazon-corretto-11.0.9.11.1-linux-x86.tar.gz](https://corretto.aws/downloads/resources/11.0.9.11.1-1/amazon-corretto-11.0.9.11.1-linux-x86.tar.gz) | `35d54f8676d97c6a40d9589050da3e20` | [Download](https://corretto.aws/downloads/resources/11.0.9.11.1-1/amazon-corretto-11.0.9.11.1-linux-x86.tar.gz.sig) |
|[Linux aarch64](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/generic-linux-install.html) |JDK    |[amazon-corretto-11.0.9.11.1-linux-aarch64.tar.gz](https://corretto.aws/downloads/resources/11.0.9.11.1-1/amazon-corretto-11.0.9.11.1-linux-aarch64.tar.gz) | `7a2c27747dbf7e028f5d9d47c3a04925` | [Download](https://corretto.aws/downloads/resources/11.0.9.11.1-1/amazon-corretto-11.0.9.11.1-linux-aarch64.tar.gz.sig) |

**Comment by eddumelendez** [comment]
Thank you! we will be updating the urls to download the new packages

**Comment by marc0der** [comment]
Thanks for getting this sorted so quickly @cliveverghese!
