### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by s-masashi** [corretto/corretto-11#146]
### Describe the bug

After following install instruction;
https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/generic-linux-install.html

I installed the following package into an AWS EC2 t4g instance(ARM64).
java-11-amazon-corretto-jdk:arm64 1:11.0.9.11-1.1

But when I ran "java --version" command, I had an unexpected error;

```
bash: /usr/bin/java: cannot execute binary file: Exec format error
```

readelf analysis shows that it looks a x86_64 binary! 

```
$ readelf -h /usr/lib/jvm/java-11-amazon-corretto/bin/java
...
Machine:                           Advanced Micro Devices X86-64
```

### Expected behavior
It should be an AArch64 binary and return java runtime version.

**Comment by benty-amzn** [comment]
Hi, thanks for contacting us about this.

We're working to make corrected packages available as soon as possible.

As a workaround, the previous version of 11.0.9 can be installed:

- `apt-get install java-11-amazon-corretto-jdk=1:11.0.9.11-1` for `.deb` based systems
- `yum install java-11-amazon-corretto-devel-1:11.0.9.11-1.aarch64` for `.rpm` based systems

Note that performing a system upgrade will still pull the latest (currently broken) versions of these artifacts.

**Comment by lutkerd** [comment]
Hi, 
We have updated the apt and yum repositories. The issues should now be fixed. 
We apologize for the inconvenience caused.
