### ISSUE TITLE
Date doesn't parse in Amazon Corretto 11.0.9.11.2

### ISSUE THREAD

**Issue by Michael2109** [corretto/corretto-11#147]
We've had a test start failing that checks if certain dates parse since upgrading from amazon-corretto-11.0.7.10.1-windows-x64 to amazon-corretto-11.0.9.11.2-windows-x64.

I've written out a small example to show this. It passes in 11.0.7.10.1 and fails in 11.0.9.11.2.

**Example**
```
final String dateString = "16/08/2017 07:28:33 PM EST-05";

final DateTimeFormatterBuilder dateTimeFormatterBuilder = new DateTimeFormatterBuilder();
dateTimeFormatterBuilder.parseCaseInsensitive();
dateTimeFormatterBuilder.appendPattern("d/M/yyyy h:mm:ss a zX");

final DateTimeFormatter formatter = dateTimeFormatterBuilder.toFormatter();

final OffsetDateTime parsedDate = OffsetDateTime.from(formatter.parse(dateString, new ParsePosition(0)));

System.out.println(parsedDate);
```

**Exception**
```
Exception in thread "main" java.time.format.DateTimeParseException: Text '16/08/2017 07:28:33 PM EST-05' could not be parsed at index 23
    at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
    at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1916)
    at test.DateTest.main(DateTest.java:19)
```

Is this a bug in the JDK or something we're doing incorrectly?

### Platform information
    OS: Windows 10
    Version: 11.0.9.11.2

**Comment by benty-amzn** [comment]
Hi, thanks for contacting us about this.
Using the provided test case I was unable to reproduce this issue with either the zip or msi installer for Corretto 11.0.9.11.2

Could you provide a complete test case and any command line flags you're using to build or execute?

I tested on Windows 10 with this class:

```
import java.text.ParsePosition;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;


class C {
    public static void main(String[] args) {
        final String dateString = "16/08/2017 07:28:33 PM EST-05";

        final DateTimeFormatterBuilder dateTimeFormatterBuilder = new DateTimeFormatterBuilder();
        dateTimeFormatterBuilder.parseCaseInsensitive();
        dateTimeFormatterBuilder.appendPattern("d/M/yyyy h:mm:ss a zX");

        final DateTimeFormatter formatter = dateTimeFormatterBuilder.toFormatter();

        final OffsetDateTime parsedDate = OffsetDateTime.from(formatter.parse(dateString, new ParsePosition(0)));

        System.out.println(parsedDate);
    }
}
```

compiled and executed with `javac.exe C.java && java.exe C` which produced the expected output:
`2017-08-16T19:28:33-05:00`

**Comment by Michael2109** [comment]
I've just tried running this in IntelliJ in a new project (instead of Eclipse) and I get the same error with your code. 

To be sure this isn't just my work machine I've tried it on my PC at home that's also Windows 10. The URL for the download is `https://corretto.aws/downloads/resources/11.0.9.11.2/amazon-corretto-11.0.9.11.2-windows-x64.msi`. 
I installed this version and created a new project that uses it. When running your code above I get this output. 

```
"C:\Program Files\Amazon Corretto\jdk11.0.9_11\bin\java.exe" "-javaagent:F:\applications\IntelliJ IDEA Community Edition 2019.3.3\lib\idea_rt.jar=53479:F:\applications\IntelliJ IDEA Community Edition 2019.3.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Users\Michael\Desktop\Date Test\out\production\Date Test" C
Exception in thread "main" java.time.format.DateTimeParseException: Text '16/08/2017 07:28:33 PM EST-05' could not be parsed at index 23
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1916)
	at C.main(C.java:17)

Process finished with exit code 1
```

I also ran it in the terminal and output the version used. 

```
C:\Users\Michael\Desktop\Date Test\src>java --version
openjdk 11.0.9 2020-10-20 LTS
OpenJDK Runtime Environment Corretto-11.0.9.11.2 (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.11.2 (build 11.0.9+11-LTS, mixed mode)

C:\Users\Michael\Desktop\Date Test\src>javac.exe C.java && java.exe C
Exception in thread "main" java.time.format.DateTimeParseException: Text '16/08/2017 07:28:33 PM EST-05' could not be parsed at index 23
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1916)
        at C.main(C.java:17)
```

**Comment by lutkerd** [comment]
Hi, would you be able to share your locale settings and the output of `java -XshowSettings:properties -version`?

Thanks.

**Comment by Michael2109** [comment]
**Locale Settings**
```
Get-WinSystemLocale                                                                        
LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
```

**Version with settings**
```
java -XshowSettings:properties -version
Property settings:
    awt.toolkit = sun.awt.windows.WToolkit
    file.encoding = Cp1252
    file.separator = \
    java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
    java.awt.printerjob = sun.awt.windows.WPrinterJob
    java.class.path =
    java.class.version = 55.0
    java.home = C:\Program Files\Amazon Corretto\jdk11.0.9_11
    java.io.tmpdir = C:\Users\Michael\AppData\Local\Temp\
    java.library.path = C:\Program Files\Amazon Corretto\jdk11.0.9_11\bin
        C:\WINDOWS\Sun\Java\bin
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\Program Files\cmder\vendor\conemu-maximus5\ConEmu\Scripts
        C:\Program Files\cmder\vendor\conemu-maximus5
        C:\Program Files\cmder\vendor\conemu-maximus5\ConEmu
        C:\Program Files\Amazon Corretto\jdk11.0.9_11\bin
        C:\Program Files (x86)\Common Files\Oracle\Java\javapath
        C:\ProgramData\Oracle\Java\javapath
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\
        C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
        C:\Program Files\Git\cmd
        C:\ProgramData\chocolatey\bin
        C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\
        C:\Program Files (x86)\GtkSharp\2.12\bin
        C:\Program Files\PuTTY\
        C:\Program Files\LLVM\bin
        C:\Program Files\CMake\bin
        C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
        C:\Program Files (x86)\ZeroTier\One\
        C:\Program Files\Java\jdk1.8.0_101\bin
        C:\Program Files\pkg-config\pkg-config-lite-0.28-1\bin
        C:\Program Files\LibZip
        C:\WINDOWS\System32\OpenSSH\
        C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
        C:\Program Files\erl10.3\bin
        C:\Program Files (x86)\Elixir\bin
        C:\Users\Michael\.mix\escripts
        C:\Program Files\PostgreSQL\11\bin
        C:\Program Files\nodejs\
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\
        C:\WINDOWS\System32\OpenSSH\
        C:\Program Files\Git LFS
        C:\Users\Michael\AppData\Roaming\local\bin
        C:\Users\Michael\.cargo\bin
        C:\Users\Michael\AppData\Local\Programs\minghc-7.10.2-x86_64\switch
        C:\Users\Michael\AppData\Local\Programs\minghc-7.10.2-x86_64\git-2.4.5.1\cmd
        C:\Users\Michael\AppData\Local\Programs\minghc-7.10.2-x86_64\git-2.4.5.1\usr\bin
        C:\Users\Michael\AppData\Local\Programs\minghc-7.10.2-x86_64\ghc-7.10.2\mingw\bin
        C:\Users\Michael\AppData\Local\Programs\minghc-7.10.2-x86_64\ghc-7.10.2\bin
        C:\Users\Michael\AppData\Local\Programs\minghc-7.10.2-x86_64\bin
        C:\Users\Michael\AppData\Roaming\cabal\bin
        C:\Users\Michael\AppData\Local\Microsoft\WindowsApps
        C:\Program Files\JetBrains\JetBrains Rider 2019.2.2\bin
        C:\Users\Michael\AppData\Roaming\npm
        C:\Users\Michael\AppData\Local\Microsoft\WindowsApps
        .
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 11.0.9+11-LTS
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 11
    java.vendor = Amazon.com Inc.
    java.vendor.url = https://aws.amazon.com/corretto/
    java.vendor.url.bug = https://github.com/corretto/corretto-11/issues/
    java.vendor.version = Corretto-11.0.9.11.2
    java.version = 11.0.9
    java.version.date = 2020-10-20
    java.vm.compressedOopsMode = Zero based
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 11
    java.vm.vendor = Amazon.com Inc.
    java.vm.version = 11.0.9+11-LTS
    jdk.debug = release
    line.separator = \r \n
    os.arch = amd64
    os.name = Windows 10
    os.version = 10.0
    path.separator = ;
    sun.arch.data.model = 64
    sun.boot.library.path = C:\Program Files\Amazon Corretto\jdk11.0.9_11\bin
    sun.cpu.endian = little
    sun.cpu.isalist = amd64
    sun.desktop = windows
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = Cp1252
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    sun.os.patch.level =
    sun.stderr.encoding = cp850
    sun.stdout.encoding = cp850
    user.country = GB
    user.dir = C:\Program Files\cmder
    user.home = C:\Users\Michael
    user.language = en
    user.name = Michael
    user.script =
    user.timezone =
    user.variant =

openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment Corretto-11.0.9.11.2 (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.11.2 (build 11.0.9+11-LTS, mixed mode)
```

**Comment by lutkerd** [comment]
Thank you for the information. Changing user.country to GB allowed me to reproduce the issue on 11.0.9 on multiple platforms and with multiple JDK vendor distributions. This is a change in the upstream code and we are trying to identify the root cause. Some abbreviations are failing while other like PST do work. We will update when we have more information.

**Comment by JackPGreen** [comment]
> Thank you for the information. Changing user.country to GB allowed me to reproduce the issue on 11.0.9 on multiple platforms and with multiple JDK vendor distributions. This is a change in the upstream code and we are trying to identify the root cause. Some abbreviations are failing while other like PST do work. We will update when we have more information.

@lutkerd is there any update to this, please? I can still reproduce this in 11.0.10.9.1.

**Comment by lutkerd** [comment]
I apologize for not updating this issue sooner. The behavior is caused by these issues: [JDK-8236548](https://bugs.openjdk.java.net/browse/JDK-8236548) and [JDK-8234347](https://bugs.openjdk.java.net/browse/JDK-8234347). The COMPAT timezones in the code are no longer copied over for all locales. There is a [comment from Naoto Sato](https://bugs.openjdk.java.net/browse/JDK-8236548?focusedCommentId=14318499&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14318499) on one of the issues "The fallback implementation first looks for the entry in CLDR. If there is an array of tz names for the locale, then use it (and look for parent locale's resources if some of the elements are missing). However, if there is no array for the locale, it will look for COMPAT's resources." The [en_GB locale](https://github.com/corretto/corretto-11/blob/007a69c44191499e7f7f24608796f45dc209bd25/src/jdk.localedata/share/classes/sun/util/cldr/resources/common/main/en_GB.xml#L399) does have timezoneNames defined, so it does not fallback to the COMPAT.

You can return to the old behavior by adding '-Djava.locale.providers=COMPAT,CLDR' to your command line, alternatively you can test in a single locale regardless of the host machines locale with '-Duser.country=US'.

**Comment by JackPGreen** [comment]
> I apologize for not updating this issue sooner. The behavior is caused by these issues: [JDK-8236548](https://bugs.openjdk.java.net/browse/JDK-8236548) and [JDK-8234347](https://bugs.openjdk.java.net/browse/JDK-8234347). The COMPAT timezones in the code are no longer copied over for all locales. There is a [comment from Naoto Sato](https://bugs.openjdk.java.net/browse/JDK-8236548?focusedCommentId=14318499&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14318499) on one of the issues "The fallback implementation first looks for the entry in CLDR. If there is an array of tz names for the locale, then use it (and look for parent locale's resources if some of the elements are missing). However, if there is no array for the locale, it will look for COMPAT's resources." The [en_GB locale](https://github.com/corretto/corretto-11/blob/007a69c44191499e7f7f24608796f45dc209bd25/src/jdk.localedata/share/classes/sun/util/cldr/resources/common/main/en_GB.xml#L399) does have timezoneNames defined, so it does not fallback to the COMPAT.
> 
> You can return to the old behavior by adding '-Djava.locale.providers=COMPAT,CLDR' to your command line, alternatively you can test in a single locale regardless of the host machines locale with '-Duser.country=US'.

Thank you for the update :)

**Comment by lutkerd** [comment]
@Michael2109 I just wanted to add 1 more quick possible solution. Since you are seeing this in a failing test and not production code, it may be simplest to update the specific tests that assume a US locale to explicitly use the locale in the `DateTimeFormatBuilder` with `final DateTimeFormatter formatter = dateTimeFormatterBuilder.toFormatter(Locale.US);`

**Comment by lutkerd** [comment]
No recent updates and multiple workarounds have been provided. If there are more questions the issue can be reopened.

**Comment by concilioinvest** [comment]
When using corretto-11 (11.0.6) the month is formatted with a dot `feb.` instead of `feb`. When running the application with corretto-1.8 (1.8.0._242) the month is formatted correctly, thus `feb` without the dot.
Adding '-Djava.locale.providers=COMPAT,CLDR' solved the problem in corretto-11, thus also displaying without the dot appended to month. 

```
-Duser.timezone=UTC -Dfile.encoding=UTF8 -Duser.region=NL -Duser.language=nl 
```

**Comment by concilioinvest** [comment]
I found that in version 33 of CLDR the Dutch language is indeed with a dot annotated, but this is removed in version 42 of CLDR.


https://www.unicode.org/cldr/cldr-aux/charts/33/verify/dates/nl.html

https://unicode-org.github.io/cldr-staging/charts/42/verify/dates/nl.html

**Comment by Rudometov** [comment]
The versions you mention worry me a lot. 11.0.6 and 8b242 are very very old. Please consider moving to the latest (which are currently [11.0.18](https://github.com/corretto/corretto-11/releases/) and [8.362](https://github.com/corretto/corretto-8/releases/))

**Comment by JackPGreen** [comment]
> The versions you mention worry me a lot. 11.0.6 and 8b242 are very very old. Please consider moving to the latest (which are currently [11.0.18](https://github.com/corretto/corretto-11/releases/) and [8.362](https://github.com/corretto/corretto-8/releases/))

are you aware this issue is over two years old? At time of posting those versions were current.

**Comment by Rudometov** [comment]
> > The versions you mention worry me a lot. 11.0.6 and 8b242 are very very old. Please consider moving to the latest (which are currently [11.0.18](https://github.com/corretto/corretto-11/releases/) and [8.362](https://github.com/corretto/corretto-8/releases/))
> 
> are you aware this issue is over two years old? At time of posting those versions were current.

This one is 1 day old: https://github.com/corretto/corretto-11/issues/147#issuecomment-1447916113
