### ISSUE TITLE
Java Version  now returns 11.0.9.1 also for Linux

### ISSUE THREAD

**Issue by SvenMarquardt5772** [corretto/corretto-11#151]
### Describe the bug
In the Changelog it says the new patch version is only for mac. But it is now also in the linux version. Because of this some of our librarys crash.  They try to parse the version string and do not anticipate a .1 after the 9. 

### To Reproduce
Update to the latest corretto version. Try to run jetty. 

### Expected behavior
The application behaviour should not change after a patch update.

### Screenshots

![grafik](https://user-images.githubusercontent.com/60098343/98952955-5b79ce80-24fc-11eb-9079-0c1a44900dec.png)

### Platform information
    OS: Amazon Linux 2
    Version 4.14.186-146.268.amzn2.x86_64

### Additional context
The patch version should not be in the java version output

**Comment by AdrianMetzner1234** [comment]
Exception thrown by jetty: 
` java.lang.IllegalArgumentException: Invalid Java version 11.0.9.1
at org.eclipse.jetty.util.JavaVersion.parseJDK9(JavaVersion.java:71)`

**Comment by SvenMarquardt5772** [comment]
Problem with old jetty version
