### ISSUE TITLE
Corretto 11.0.10.9.1 and BouncyCastle < 1.66 incompatibility

### ISSUE THREAD

**Issue by alvdavi** [corretto/corretto-11#168]
OpenJDK 11.0.9+10 includes a backport of [JDK-8171279](https://bugs.openjdk.java.net/browse/JDK-8171279).

When this patch was initially included in OpenJDK13 it exposed a series of compatibility issues (https://github.com/bcgit/bc-java/issues/589 and https://github.com/bcgit/bc-java/issues/620) that were addressed in BouncyCastle 1.66 release.

If you're using an older version of BouncyCastle you might see the same errors reported on the issues. If you use and old version of BouncyCastle, we recommend you update both, BouncyCastle and Corretto11, together.

**Comment by paulpearcy** [comment]
You mention recommending updating BouncyCastle and Corretto11 together. Is it problematic to update BouncyCastle first? Thanks!

**Comment by alvdavi** [comment]
We are not aware of any issue between up to date BouncyCastle and older versions of Corretto, but we always recommend to keep Corretto up to date.
