### ISSUE TITLE
ZGC not available on Windows with Corretto 11

### ISSUE THREAD

**Issue by mondain** [corretto/corretto-11#169]
### Describe the bug
Attempting to start the JVM on windows with ZGC fails.

### To Reproduce
Apply `-XX:+UnlockExperimentalVMOptions -XX:+UseZGC` to your java opts and launch your build.

### Expected behavior
Run as expected, like it does on Linux

### Platform information
    OS: Windows 10
    Version 11.0.9.1.12.1

### Additional context
Same compilation works just fine on Linux

**Comment by AzeemJiva** [comment]
Hi Paul,
  ZGC for Windows support is only available in JDK14 and later.  The relevant JEP:  https://openjdk.java.net/jeps/365

**Comment by mondain** [comment]
@AzeemJiva will it continue to work for Linux on 11?

**Comment by AzeemJiva** [comment]
Yes it will

**Comment by mondain** [comment]
Thank you!
