### ISSUE TITLE
Unrecognized VM option 'UseShenandoahGC' in java-11-amazon-corretto from yum

### ISSUE THREAD

**Issue by paiyar** [corretto/corretto-11#173]
### Describe the bug

Encountered `Unrecognized VM option 'UseShenandoahGC'` when passing the flag ` -XX:+UseShenandoahGC` In java-11-amazon-corretto-headless-11.0.10+9-1 pulled from yum. 

**NOTE**: This does not occur if I use https://corretto.aws/downloads/resources/11.0.10.9.1/amazon-corretto-11.0.10.9.1-linux-x64.tar.gz (the latest release) directly.

### To Reproduce
Per https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/amazon-linux-install.html , install the following:

```
yum install -y java-11-amazon-corretto-headless-11.0.10+9-1.amzn2.x86_64 
```

```
bash-4.2# java --version
openjdk 11.0.10 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
```

Attempt to use Shenandoah GC:

```
bash-4.2# java -XX:+UseShenandoahGC  --version
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

When pulling https://corretto.aws/downloads/resources/11.0.10.9.1/amazon-corretto-11.0.10.9.1-linux-x64.tar.gz directly:

```
wget https://corretto.aws/downloads/resources/11.0.10.9.1/amazon-corretto-11.0.10.9.1-linux-x64.tar.gz
tar -xvf amazon-corretto-11.0.10.9.1-linux-x64.tar.gz
```

```
./amazon-corretto-11.0.10.9.1-linux-x64/bin/java --version
openjdk 11.0.10 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
```

```
./amazon-corretto-11.0.10.9.1-linux-x64/bin/java -XX:+UseShenandoahGC --version
openjdk 11.0.10 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
```

### Expected behavior

That the flag is recognized per https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-corretto-quarterly-updates-now-available/

### Platform information
    OS: Amazon Linux 2
    Version: java-11-amazon-corretto-headless-11.0.10+9-1.amzn2.x86_64

**Comment by davecurrie** [comment]
Thanks for letting us know, we're looking into it.

**Comment by lutkerd** [comment]
Hi, we are working on certifying a new build that resolve this issue. I will update again when the build is available for direct download and when it is in the Amazon Linux Yum repositories.

**Comment by paiyar** [comment]
Thank you @davecurrie & @lutkerd ! Sincerely appreciate the prompt responses.

**Comment by lutkerd** [comment]
New Amazon Linux 2 RPMs have been published to https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html that have ShenandoahGC available.

Leaving this issue open until Yum repos are updated and verified.

**Comment by paiyar** [comment]
Any chance there's an update on the yum release? Or alternatively, any chance there are headless distributions with the fix available for consumption on Amazon Linux outside of yum?

**Comment by davecurrie** [comment]
Hi. This link from the downloads page linked above will provide a headless AL2 RPM: https://corretto.aws/downloads/latest/amazon-corretto-11-x64-al2-jre.rpm

**Comment by alvdavi** [comment]
Hi,

AL2 yum repositories have been updated.
