### ISSUE TITLE
Add AAA Certificate Services Root (2028) to cacerts

### ISSUE THREAD

**Issue by kc9wwh** [corretto/corretto-11#177]
### Is your feature request related to a problem?
As of March 29th, 2021 Apple is incorporating a new Root CA with its Push Notification Service. This service is what ensures all organizationally owned and managed Apple Devices are able to communicate and receive MDM commands. This is critical for all organizations that manage Apple devices and most organizations choose to use Amazon Corretto 11 as the preferred JDK install across various OS's. 

### Describe a solution you would like
Please add the new Sectigo AAA Certificate Services Root (2028) certs to the cacerts keystore.
https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117cL

### Describe alternatives you have considered
Currently all organizations would have to manually import these certs to the cacerts keystore manually.

### Additional context
Email from Apple Developer Relations:

> On March 29, 2021, token and certificate-based HTTP/2 connections to the Apple Push Notification service must incorporate the new root certificate ([AAACertificateServices 5/12/2020](https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117cL)) which replaces the old GeoTrust Global CA root certificate. To ensure a seamless transition and to avoid push notification delivery failures, verify that both the old and new root certificates for the HTTP/2 interface are included in the Trust Store of each of your notification servers before March 29. 
>
> Note that Apple Push Notification service SSL provider certificates issued to you by Apple do not need be to updated at this time. 
>
> [Learn more about connecting to APNs.](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/) 
>
> If you have any questions, [contact us](https:/developer.apple.com/contact/). 
>
> Best regards, 
> Apple Developer Relations

**Comment by alvdavi** [comment]
Hi,

That certificate is already present in the corretto cacerts:
https://github.com/corretto/corretto-11/blob/develop/make/data/cacerts/comodoaaaca

I've verified the fingerpint. From the url you sent
```
-> openssl x509 -in AAACertificateServices.crt -noout -fingerprint -sha256
SHA256 Fingerprint=D7:A7:A0:FB:5D:7E:27:31:D7:71:E9:48:4E:BC:DE:F7:1D:5F:0C:3E:0A:29:48:78:2B:C8:3E:E0:EA:69:9E:F4
```
From the Corretto source code:
```
-> openssl x509 -noout -in make/data/cacerts/comodoaaaca -fingerprint -sha256
SHA256 Fingerprint=D7:A7:A0:FB:5D:7E:27:31:D7:71:E9:48:4E:BC:DE:F7:1D:5F:0C:3E:0A:29:48:78:2B:C8:3E:E0:EA:69:9E:F4
```

Additionally, I can confirm this certificate makes it into the Corretto store:
```
-> keytool -list -cacerts -alias "comodoaaaca [jdk]" 2> /dev/null

comodoaaaca [jdk], Jan 1, 2004, trustedCertEntry,
Certificate fingerprint (SHA-256): D7:A7:A0:FB:5D:7E:27:31:D7:71:E9:48:4E:BC:DE:F7:1D:5F:0C:3E:0A:29:48:78:2B:C8:3E:E0:EA:69:9E:F4
```

In fact, the certificate is present in the store twice. This is because the cacerts bundled with Corretto is the union of OpenJDK default cacerts plus the certificates present in Amazon Linux 2:
```
-> keytool -list -cacerts -alias "comodoaaaservicesroot" 2> /dev/null

comodoaaaservicesroot, Jan 12, 2021, trustedCertEntry,
Certificate fingerprint (SHA-256): D7:A7:A0:FB:5D:7E:27:31:D7:71:E9:48:4E:BC:DE:F7:1D:5F:0C:3E:0A:29:48:78:2B:C8:3E:E0:EA:69:9E:F4
```

**Comment by kc9wwh** [comment]
@alvdavi interesting...I installed the latest version available earlier today on WIn2012R2 and when I checked the `cacerts` keystore the fingerprints didn't match. I will go back and check again though. Appreciate your input!

**Comment by alvdavi** [comment]
Please, reopen this issue if the certificate is not present in your installation

**Comment by kc9wwh** [comment]
Found the issue on my end, apologies for the extra work, but also much appreciated! 

![ID10T Error](https://www.joetheitguy.com/wp-content/uploads/2017/08/ID1OT.png)

**Comment by alvdavi** [comment]
For the next releaes, we plan to change how the aliases in the cacerts are handled. For example, this copy of the certificates will go from being:
```
comodoaaaca [jdk]
comodoaaaservicesroot
```
to:
```
comodoaaaca
comodoaaaservicesroot_al2
```

The idea is to keep the aliases for the certificates coming from OpenJDK unchanged, while appending al2 to those coming from Amazon Linux 2
