### ISSUE TITLE
Open JDK Font issue in Linux

### ISSUE THREAD

**Issue by asanthosh** [corretto/corretto-11#179]
Running a Java application which uses Jasper to generate the report on Open JDK 11.0.3-64 version. Application works fine on the windows where as it fails to generate the report in Linux. Appears like the JDK on linux is missing the fontconfig.properties.src & fontconfig.bfc file. As a result JDK is not able to find the fonts needed to generate the report. Application throws the below error

**INFO: Looking for binary fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.bfc**

**Feb 23, 2021 12:46:07 PM sun.awt.FontConfiguration findFontConfigFile INFO: Did not find a fontconfig file.**

Is it intentional to remove the fontconfig properties on the Linux build ?

**Comment by davecurrie** [comment]
Hi. Have you installed the fontconfig package on the Linux machine? Corretto for Linux uses the system installed fontconfig.

**Comment by asanthosh** [comment]
No, I have not installed the fontconfig package in Linux.. Let me install the package and try again.. Thanks

**Comment by asanthosh** [comment]
It did not work even after installing the fontconfig on the Linux server. Logs indicate that the JDK is looking for the font config from the JDK Lib.

> Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration <init>
INFO: Creating standard Font Configuration
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for text fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.RedHat.7.3.properties
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for binary fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.RedHat.7.3.bfc
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for text fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.RedHat.7.properties
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for binary fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.RedHat.7.bfc
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for text fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.RedHat.properties
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for binary fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.RedHat.bfc
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for text fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.7.3.properties
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for binary fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.7.3.bfc
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for text fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.7.properties
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for binary fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.7.bfc
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for text fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.properties
Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findImpl
INFO: Looking for binary fontconfig file : /tomcat/spring/java/jdk1.11.0.3-64/lib/fontconfig.bfc
**_Feb 25, 2021 9:45:54 AM sun.awt.FontConfiguration findFontConfigFile
INFO: Did not find a fontconfig file.
Feb 25, 2021 9:45:54 AM sun.font.FcFontConfiguration warning
WARNING: Failed to get info from libfontconfig_**

and here is the exception from the application logs

> Caused by: java.io.IOException: Problem reading font data.
        at java.awt.Font.createFont0(Font.java:1183) ~[?:?]
        at java.awt.Font.createFont(Font.java:1052) ~[?:?]
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.setTtf(SimpleFontFace.java:173) ~[jasperreports-6.0.3.jar:6.0.3]
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.parseFontFace(SimpleFontExtensionHelper.java:351) ~[jasperreports-6.0.3.jar:6.0.3]
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.parseFontFamily(SimpleFontExtensionHelper.java:273) ~[jasperreports-6.0.3.jar:6.0.3]
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.parseFontFamilies(SimpleFontExtensionHelper.java:237) ~[jasperreports-6.0.3.jar:6.0.3]
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.loadFontFamilies(SimpleFontExtensionHelper.java:198) ~[jasperreports-6.0.3.jar:6.0.3]
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.loadFontFamilies(SimpleFontExtensionHelper.java:167) ~[jasperreports-6.0.3.jar:6.0.3]
        at net.sf.jasperreports.engine.fonts.FontExtensionsRegistry.getExtensions(FontExtensionsRegistry.java:58) ~[jasperreports-6.0.3.jar:6.0.3]
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:109) ~[jasperreports-6.0.3.jar:6.0.3]
        at net.sf.jasperreports.engine.util.JRStyledTextParser.<clinit>(JRStyledTextParser.java:82) ~[jasperreports-6.0.3.jar:6.0.3]

**Comment by alvdavi** [comment]
Hi. The JDK will only look for that font config file after the attempts to use libfontconfig have failed (and we still want font discovery to go through libfontconfig). Could you please let me know the output of running `fc-match` on that system? Also, could you add which linux distribution and version you are using?

**Comment by asanthosh** [comment]
here is the list of files in fontconfig.

> [logs]$ cd /usr/share/fontconfig/conf.avail
[conf.avail]$ ls -ltr
total 140
-rw-r--r-- 1 root root  1691 Feb 19  2012 90-synthetic.conf
-rw-r--r-- 1 root root   263 Feb 19  2012 70-yes-bitmaps.conf
-rw-r--r-- 1 root root   263 Feb 19  2012 70-no-bitmaps.conf
-rw-r--r-- 1 root root   672 Feb 19  2012 69-unifont.conf
-rw-r--r-- 1 root root   289 Feb 19  2012 65-khmer.conf

`fc-match` did not return anything. 

this was the fontconfig package that was installed `fontconfig-2.10.95-10.el7.x86_64`

here is the Linux details. 

` cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="OpenShift Enterprise"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"
`

**Comment by alvdavi** [comment]
It is expected for `fc-match` to return something, as it should be the default font in the system. For example, on one of my test benches:
```
-> fc-match
DejaVuSans.ttf: "DejaVu Sans" "Book"
```

Some linux distributions install a default font when fontconfig is installed. I don't have a RHEL7.3 system. I did test on Centos 7.8. And there, fontconfig does indeed depend on the dejavu fonts:
```
-> yum deplist fontconfig | grep dejavu
  dependency: dejavu-sans-fonts
   provider: dejavu-sans-fonts.noarch 2.33-6.el7
  dependency: dejavu-sans-fonts
   provider: dejavu-sans-fonts.noarch 2.33-6.el7
```

Can you check if dejavu fonts are installed on the system (and if not, install them). After the installation, fc-match should return a value (you can install any font you like, it doesn't have to be the dejavu, but once fc-match returns a result, I expect the exception to go away.

**Comment by asanthosh** [comment]
thanks.. after installing the font again, it worked..
