### ISSUE TITLE
brew installation for MacOS?

### ISSUE THREAD

**Issue by hrstoyanov** [corretto/corretto-11#18]
For MacOS users, the preferred way to install Corretto (and keep it up-to-date) would be through the brew package installer. All other JDKs can be installed with brew. Please consider developing a brew cask for Corretto.

You can take a look at [AdoptOpenJDK brew integration](https://github.com/AdoptOpenJDK/homebrew-openjdk) or even join efforts with them!

**Comment by ziyiluo** [comment]
@hrstoyanov Thanks for bringing this up! We have a [similar request in Corretto 8](https://github.com/corretto/corretto-8/issues/42). How to update homebrew as part of our release process is still under discussion. We will update this issue when we have any update.

**Comment by davecurrie** [comment]
Closing in favor of the Corretto 8 issue, both will be treated as a whole
