### ISSUE TITLE
Unrecognized VM option 'UseShenandoahGC' in amazoncorretto:11-alpine from docker

### ISSUE THREAD

**Issue by charlie-harvey** [corretto/corretto-11#187]
### Describe the bug
Encountered Unrecognized VM option 'UseShenandoahGC' when passing the flag `-XX:+UseShenandoahGC` in `amazoncorretto:11-alpine` pulled from docker.

NOTE: This does not occur if I use `amazoncorretto:11`.

### To Reproduce
```sh
docker run amazoncorretto:11-alpine java -XX:+UseShenandoahGC --version
Unable to find image 'amazoncorretto:11-alpine' locally
11-alpine: Pulling from library/amazoncorretto
Digest: sha256:0ab02867f1b7a0bef119f284a2922f20f7aa50dd501e023b063a9ca2ac1c959d
Status: Downloaded newer image for amazoncorretto:11-alpine
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

### Expected behavior
```sh
docker run amazoncorretto:11 java -XX:+UseShenandoahGC --version
openjdk 11.0.10 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
```

### Additional context
Works in `amazoncorretto:11`, `amazoncorretto:15`, `amazoncorretto:15-alpine`, `amazoncorretto:16`, `amazoncorretto:16-alpine`

**Comment by alvdavi** [comment]
Hi,

thanks for reporting this. Corretto builds with a version number higher than 11.0.11.0.0 will have Shenandoah enabled in Alpine. This was added in commit https://github.com/corretto/corretto-11/commit/a300ecf7880df1c80678f9ee371b4716a47b75e4

We expect 11.0.11 based builds to be released and published to Dockerhub during this week.

**Comment by charlie-harvey** [comment]
Great. Thanks so much.
