### ISSUE TITLE
Request that corretto image be part of the verified amazon account

### ISSUE THREAD

**Issue by Krishna-Kumar-2021** [corretto/corretto-11#194]
Thank you for taking the time to help improve OpenJDK and Corretto 11.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your idea concerns OpenJDK 11
and is not specific to Corretto 11
we ask that you propose it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system](https://bugs.openjdk.java.net/) or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or [update project](http://mail.openjdk.java.net/mailman/listinfo/jdk-updates-dev)).

If your proposal is specific to Corretto 11,
then you are in the right place.
Please proceed with the following.

### Is your feature request related to a problem?
Current Corretto image is not part of the verified amazon account. 

### Describe a solution you would like
Kindly include  corretto image (https://gallery.ecr.aws/ews-network/amazoncorretto) as part of the  a verified account like the amazon linux image https://gallery.ecr.aws/amazonlinux/amazonlinux. 

### Describe alternatives you have considered
Please provide a clear and concise description
of any alternative solutions or features you have considered.

**Comment by davecurrie** [comment]
Hi.

That image is not built by us and is not official. We recommend not using it.

We have it on our roadmap to provide Corretto in public ECR soon. That will be a verified account. For now, please use our existing ECR instance. Instructions are at https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/docker-install.html
