### ISSUE TITLE
Information on Class file compatibility

### ISSUE THREAD

**Issue by mondain** [corretto/corretto-11#2]
The feature I would like addressed is the apparent lack of information regarding class file / binary compatibility. In a nut-shell I'd like to know if my code compiled in a jar with Corretto 11 will execute on someones installed Oracle or OpenJDK 11 or an older version such as 8.

A solution would be to provide the information in a developer document or the project repo readme.

## References
[Java Class file](https://en.wikipedia.org/wiki/Java_class_file)
[JSR-202](https://www.jcp.org/en/jsr/detail?id=202)
[Update class file version to 53 for JDK-9](https://bugs.openjdk.java.net/browse/JDK-8148785)

**Comment by bernd-aws** [comment]
Yes, code compiled by Amazon Corretto 11 is expected to be compatible with any other JDK 11.
Java 11 code will not run on JDK 8. You can use the javac flag “-source 8” in JDK 11 to compile Java 8 code.
 
Thanks for bringing this up: we will augment our documentation to better indicate what compatibilities to expect.
