### ISSUE TITLE
Java application crashed with Inconsistency detected

### ISSUE THREAD

**Issue by jpshvets** [corretto/corretto-11#203]
We have a Java application that's running on EC2 with OpenJDK Coretto 11.0.12.7.1. Please find the details of the issue below: 
Inconsistency detected by ld.so: ../elf/dl-tls.c: 488: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!

bash-4.2# java --version
openjdk 11.0.12 2021-07-20 LTS
OpenJDK Runtime Environment Corretto-11.0.12.7.1 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.12.7.1 (build 11.0.12+7-LTS, mixed mode)
bash-4.2# ldd --version
ldd (GNU libc) 2.26

bash-4.2# ldd --version
ldd (GNU libc) 2.26

**Comment by matenhagen** [comment]
This is likely related to https://sourceware.org/bugzilla/show_bug.cgi?id=19329

**Comment by alvdavi** [comment]
I agree, it does seem to be that bug.

The bug is fixed in glibc 2.34, which is a very new version of glibc, still not available in most distributions, but once it is updated, it should fix this issue.
