### ISSUE TITLE
JVM on graviton2 does not perform better than AMD64

### ISSUE THREAD

**Issue by balusarakesh** [corretto/corretto-11#205]
### Describe the bug

Hi,
We started experimenting with graviton2 EC2 instances for EKS and we are seeing that multiple pods are being restarted for one of our java services

 - we started experimenting with corretto image 11.0.9 and we noticed that pods were restarting with the error code `Reason: Error - exit code: 137` which generally means pods are getting killed for using more than allocated memory (`but we don't see any OOMKilled errors though`) - we don't see any kind of errors in pod logs, pods just respond with `503` and restart after a couple minutes at peaks
 - later we updated the image to the corretto version 11.0.12 and then we noticed a drop in pod restarts but now the pods are restarting with error code `143`  - this time we see errors like (`org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name` ,` [reactor-http-epoll-3] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler user-segmentation-application - [d015b326-425512] 500 Server Error for HTTP GET` - this seems like the pod is just not accepting any more traffic)
 - we compared the JVM profile metrics (Datadog) between AMD64 and ARM64 and noticed that they are all very similar to each other except GC Avg heap remaining  and GC pause duration
 - CPU usage and memory usage on both architectures is quite similar (each pod has 3 cores and 8GB of RAM as requests and 8 cores and 16 GB of RAM as limits) 
AMD64 pod uses `c5.9xlarge` and ARM64 uses `c6g.8xlarge` instance types

screenshot1: ARM64 avg heap remaining  - as you can see heap remaining on ARM64 is very consistent around 400-500 MB
screenshot2: ARM64 avg GC pause duration - not very consistent and fluctuates quite a lot
screenshot3: AMD64 avg heap remaining  - most of the pods have between 500-700 MB remaining and only some pods have around 400-500 MB
screenshot4: AMD64 avg GC pause duration - very consistent GC pauses

### Expected behavior
We were expecting improved performance on pods running on graviton2 nodes.

### Screenshots
![screenshot4](https://user-images.githubusercontent.com/17168699/132384630-e636c191-867e-4598-b51d-0f67aca7fda7.png)
![screenshot3](https://user-images.githubusercontent.com/17168699/132384636-696b1a28-e11b-40aa-a2d7-c449934f9c12.png)
![screenshot2](https://user-images.githubusercontent.com/17168699/132384643-ae101eb8-38de-4644-b54a-7a1c47de30a5.png)
![screnshot1](https://user-images.githubusercontent.com/17168699/132384644-57249570-fe63-48ac-bb6e-2d7a02819159.png)

### Platform information
ARM64:
AMI: `bottlerocket-aws-k8s-1.18-aarch64-v1.1.4-f5239c49 (ami-0b39bc602912155ee)` (we also tried the bottlerocket AMI `1.0.5` used by AMD64 and saw same results
corretto image: `11.0.12`

AMD64:
AMI:  `bottlerocket-aws-k8s-1.18-x86_64-v1.0.5-f306b954 (ami-03940c85c11991cb6)`
corretto image: `11.0.12`

**Comment by eastig** [comment]
Hi Rakesh,
Without additional information it is difficult to answer what is the root cause.
Do you use the same EKS configuration on c5 and c6g?
On c6g, have you tried to reduce a number of pods to fix the errors?
Do you have metrics like latency which have differences between c5 and c6g?
I also recommend to read: https://github.com/aws/aws-graviton-getting-started/blob/main/perfrunbook/graviton_perfrunbook.md

Thanks,
Evgeny

**Comment by balusarakesh** [comment]
we believe this could be an issue with our internal database acting up while testing ARM64 pods
