### ISSUE TITLE
The Windows Installer does not set file association for jar files

### ISSUE THREAD

**Issue by Syphist** [corretto/corretto-11#21]
### Is your feature request related to a problem?
Jar files cannot be double clicked in Windows to open them like they can be with Oracle's JRE.

### Describe a solution you would like
For the installer to automatically set the file association to jar files to run like an executable when double clicked

### Describe alternatives you have considered
Not applicable.

### Additional context
It appears this was already fixed in Corretto 8 according to this issue: [https://github.com/corretto/corretto-8/issues/43](url)

**Comment by davecurrie** [comment]
Hi @Syphist. Thanks for the feedback, we'll review and get back on this issue soon.

**Comment by Brodieman** [comment]
We are having the same issue but it's not constant.  Some of our computers will work when double clicking on a JAR file some won't.  I can run java -jar myjar.jar and it will run the JAR file but not double clicking

**Comment by Syphist** [comment]
Thanks for the input @Brodieman, I have tried it on another computer I have access to and it works, if the jar file has no spaces in the name. It appears that when running that through a command prompt it does not preserve the quotes. I played around with the command and this modification of the last line works like a charm.

`reg add "HKEY_CLASSES_ROOT\jarfile\Shell\Open\Command" /f /ve /d "\"C:\Program Files\Amazon Corretto\jdk11.0.3_7\bin\javaw.exe\" -jar \"%1\" %*"`

**Comment by yoroto** [comment]
Fixed in 11.0.5.
