### ISSUE TITLE
Need instruction to install JDK on Arm32 processor

### ISSUE THREAD

**Issue by permuddannaya** [corretto/corretto-11#210]
tried the following step [Link](https://www.element14.com/community/docs/DOC-54112/l/java-on-the-raspberry-pi) , but was not successful

**Comment by earthling-amzn** [comment]
Thank you for filing a ticket with us. It would be helpful if you could provide more detail. Please confirm the Corretto release version (amazon-corretto-11.0.12.7.1-linux-armv7.tar.gz is the latest at the time of this writing) you're using and what platform you are installing on. If you have any console output from the error, that would also be helpful.

**Comment by navyxliu** [comment]
Could you follow this [instruction](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/generic-linux-install.html)? 
Any problem do you encounter when you install Corretto-11 armv7 build?

**Comment by greencustard** [comment]
I am trying to install Amazon Corretto on a Raspberry Pi CM3+ using this download:
https://corretto.aws/downloads/latest/amazon-corretto-11-arm-linux-jdk.tar.gz
I have to use this as it is the only option for aarch32. I have extracted the contents, but there are no instructions of how to install the JDK. I manually overlayed the contents of ./amazon-corretto-11.0.13.8.1-linux-armv7/bin into /usr/bin and
./amazon-corretto-11.0.13.8.1-linux-armv7/bin into /usr/lib
However I see the following errors from journaltctl when Greengrass starts:
java/lang/NoClassDefFoundError: java/lang/Object
I appreciate that what I have done is, erm, not ideal, but this is through lack of clear installation instructions.
Can someone please write some?
Update: Hacking paths to the Java install didn't work and Greengrass v2 failed to run. I have installed as follows:
```
sudo apt-get install java-common
sudo apt install default-jdk
```
This is working, but I have another embedded target, built using Yocto, that uses Corretto and I wanted to keep them the same as far as possible.

**Comment by benty-amzn** [comment]
Hi, you should be able to accomplish this by extracting the tgz to some directory ([Oracle's documentation](https://java.com/en/download/help/linux_x64_install.html) uses `/usr/java` as an example) and setting `JAVA_HOME`

E.g. on macos, I have
```
java -version                                                                                                                                                                                                                                                                                                                                  
openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Corretto-17.0.1.12.1 (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.1.12.1 (build 17.0.1+12-LTS, mixed mode, sharing)
```

If I then download the macos tgz to `~/java` and set `JAVA_HOME`:
```
mkdir -p ~/java && cd ~/java
wget https://corretto.aws/downloads/resources/11.0.13.8.1/amazon-corretto-11.0.13.8.1-macosx-x64.tar.gz
tar xf amazon-corretto-11.0.13.8.1-macosx-x64.tar.gz
export JAVA_HOME="$(pwd)/amazon-corretto-11.jdk/Contents/Home/"
java -version
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Corretto-11.0.13.8.1 (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.13.8.1 (build 11.0.13+8-LTS, mixed mode)
```

The directory structure will be somewhat different on linux, so adapt as needed - `JAVA_HOME` should be set to the parent directory of `bin`, so that `ls ${JAVA_HOME}` produces output like `bin conf include jmods legal lib man release`

Once you have `JAVA_HOME` set appropriately, you can add it to your `.bashrc` (or other shell rc file)
