### ISSUE TITLE
Please offer .xz compression for Corretto release tarballs

### ISSUE THREAD

**Issue by jmillikin** [corretto/corretto-11#22]
For the tarballs on https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html, please provide them with xz compression in addition to (or instead of) gzip. The xz format provides materially better compression ratios at the cost of increased compression time.

For example, `amazon-corretto-11.0.3.7.1-macosx-x64.tar.gz` recompressed with `xz -4e` is reduced from 185 MB to 159 MB, a 14% reduction:
```
$ gzip -d --keep amazon-corretto-11.0.3.7.1-macosx-x64.tar.gz
$ xz --keep --compress -4e amazon-corretto-11.0.3.7.1-macosx-x64.tar
$ ls -o amazon-corretto-11.0.3.7.1-*
-rw-r--r--@ 1 john  306257920 Apr 29 22:47 amazon-corretto-11.0.3.7.1-macosx-x64.tar
-rw-r--r--@ 1 john  184892496 Apr 29 22:47 amazon-corretto-11.0.3.7.1-macosx-x64.tar.gz
-rw-r--r--@ 1 john  158906996 Apr 29 22:47 amazon-corretto-11.0.3.7.1-macosx-x64.tar.xz
```

This request also applies to Corretto 8, which `xz -4e` reduces from 115 MB to 97 MB (15.6% reduction):
```
$ gzip -d --keep amazon-corretto-8.212.04.2-macosx-x64.tar.gz
$ xz --keep --compress -4e amazon-corretto-8.212.04.2-macosx-x64.tar
$ ls -o amazon-corretto-8.212.04.2-*
-rw-r--r--@ 1 john  214241280 Apr 29 23:05 amazon-corretto-8.212.04.2-macosx-x64.tar
-rw-r--r--@ 1 john  114842259 Apr 29 23:05 amazon-corretto-8.212.04.2-macosx-x64.tar.gz
-rw-r--r--@ 1 john   96845064 Apr 29 23:05 amazon-corretto-8.212.04.2-macosx-x64.tar.xz
```

**Comment by davecurrie** [comment]
@jmillikin Thanks for your request. There are plenty of possible ways we could choose to distribute Corretto and we have chosen the .tar.gz format because it is widespread and fairly standard in the JDK ecosystem. I would like to understand why this size difference is important, can you share your concerns?

Thanks.

**Comment by EricEdens** [comment]
I'm going to go ahead and close this since we haven't heard back for a couple of weeks. Feel free to re-open though.
