### ISSUE TITLE
64 bit .dll file in Corretto OpenJDK 11 for windows x86

### ISSUE THREAD

**Issue by kefeisu** [corretto/corretto-11#238]
### Describe the bug
There is a 64 bit `.dll` file in the 32 bit version of Corretto 11 for windows (Corretto JDK 11 for windows x86).
(api-ms-win-crt-runtime-l1-1-0.dll is one of the culprits, there may be more)
This breaks all bin executables on windows 7 32 bit (and possibly other 32 bit OSes)
![image](https://user-images.githubusercontent.com/20504367/149253190-ef65e6c1-dd5b-44ef-bb9a-73a3ec17a00e.png)

### To Reproduce
Download Amazon Corretto on a fresh installation of windows 7 32 bit system and try to run java.exe (or any .exe executable). Windows will complain about a faulty `.dll` file. 

### Expected behavior
Java (and all other executables) should work out of the box

### Screenshots
See above

### Platform information
    OS: Windows 7 32 bit
    Version Corretto 11.0.13

### Additional context
Removing all api-ms*.dll files will fix this issue on windows 7 (as it will default to using the native system32 .dll files if present).
Other windows OSes (such as windows 10 32 bit) will use the native system32 .dll files automatically and therefore bypass this issue. 

Can't find any references to those .dll files in the corretto repo (Though I think this is a corretto issue).
Sorry if this is an OpenJDK bug and not Corretto bug.

**Comment by TianminShi** [comment]
Hi kefeisu, Thank you for reporting this bug. you can expect this to be fixed in the incoming Q1 release which should be out in a few days.

**Comment by benty-amzn** [comment]
This should be resolved in the q1 release, which is available now. Please let us know if you encounter any further issues.
