### ISSUE TITLE
Debian jinfo file

### ISSUE THREAD

**Issue by tomposmiko** [corretto/corretto-11#25]
The same as for [corretto8](https://github.com/corretto/corretto-8/issues/63) so I copy the complete description here.

Unlike most other java distributions for debian, corretto does not provide a .jinfo file.
This file is used by update-java-alternatives to switch all java related symlinks to another distribution.

It also means that update-java-alternatives --list does not show corretto.

The jinfo files are installed in /usr/lib/jvm/.${package-name}.jinfo.
I do not think the format is somewhere specifically documented. I think the source of the update-java-alternatives script is the best reference together with other packaging scripts.

It would be nice if we could just type update-java-alternatives -s java-11-amazon-corretto to switch to corretto.

**Comment by EricEdens** [comment]
Thanks for the report! It looks like we only fixed this in 8. I've added this to our 11.0.4 milesone.
