### ISSUE TITLE
Sigsegv after upgrade from 11.0.4 to 11.0.5 docker container

### ISSUE THREAD

**Issue by IRus** [corretto/corretto-11#257]
### Describe the bug
Application failing after a minute running on 11.0.5

```
6:12:49.614 [grpc-default-executor-0] INFO  c.g.a.googleads.lib.request.summary - SUCCESS REQUEST SUMMARY. Method: google.ads.googleads.v10.services.GoogleAdsService/Mutate, Endpoint: googleads.googleapis.com:443, CustomerID: *redacted*, Request
ID: *redacted*, ResponseCode: OK, Fault: null.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f74fe245491, pid=1, tid=29
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.15.9.1 (11.0.15+9) (build 11.0.15+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.15.9.1 (11.0.15+9-LTS, mixed mode, tiered, compressed oops, shenandoah gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xccb491]  PhaseIterGVN::transform_old(Node*)+0x151
#
# Core dump will be written. Default location: //core.1
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
#
# Compiler replay data is saved as:
# /tmp/replay_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-11/issues/
#

[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007f74feb7723b]
```

### To Reproduce
No reproducer

### Platform information
    OS: `amazoncorretto:11.0.15`
    Version: Corretto-11.0.15.9.1

### Additional context
JAVA_OPTS "-Djdk.module.illegalAccess=permit -XX:+PrintFlagsFinal -XX:+UseShenandoahGC -Xmx2048m -Djava.security.egd=file:/dev/urandom"

> For VM crashes, please attach the error report file. By default the file name is `hs_err_pidpid.log`, where pid is the process ID of the process.

In progress

**Comment by lutkerd** [comment]
Hi, thanks for reporting the issue. Does this happen every time or intermittently? 

I don't see any existing issues for this with a similar configuration, we will need the hs_err file to dig in further.

**Comment by navyxliu** [comment]
hi, @IRus , 
From you options, the only uncommon part is you are using Shenandoah GC. Can you still trigger the same problem with other GCs? 

We really need the hs_err_pid1.log and replay_pid1.log to study this crash. If you can save the core.1 file and share with us , that would be even better.

**Comment by lutkerd** [comment]
Closing issue, please reopen is there is something we can help with.
