### ISSUE TITLE
Export Control Classification Number (ECCN)

### ISSUE THREAD

**Issue by HugoReis** [corretto/corretto-11#26]
What it the Export Control Classification Number (ECCN) for Amazon Corretto 11?

**Comment by EricEdens** [comment]
Good question. Tracking down the right person to help with this.

**Comment by ziyiluo** [comment]
@HugoReis Thank you for your patience. Corretto is an open source project and does not have or require an ECCN. Feel free to reopen the issue if you have further questions.
