### ISSUE TITLE
Information about Corretto 11.0.16 issue

### ISSUE THREAD

**Issue by rccha** [corretto/corretto-11#281]
We identified an issue with systems using Amazon Corretto 11.0.16 (July release). This is reproducible in servers using 11.0.16 and fail within C2 compilation of sun.security.ssl.SSLEngineInputRecord::decodeInputRecord. We are currently investigating this issue. A similar issue is reported on JBS - [JDK-8291665](https://bugs.openjdk.org/browse/JDK-8291665).

**Comment by benty-amzn** [comment]
Closing as a duplicate of #281. Tracked upstream on [JDK-8292260](https://bugs.openjdk.org/browse/JDK-8292260), and a patch release [11.0.16.1](https://bugs.openjdk.org/browse/JDK-8292367) will be available soon.

**Comment by benty-amzn** [comment]
Tracked upstream on [JDK-8292260](https://bugs.openjdk.org/browse/JDK-8292260), and a patch release [11.0.16.1](https://bugs.openjdk.org/browse/JDK-8292367) will be available soon.

**Comment by olivergillespie** [comment]
Fixed in 11.0.16.9.1 - see https://github.com/corretto/corretto-11/blob/release-11.0.16.9.1/CHANGELOG.md.
