### ISSUE TITLE
UseShenandoahGC not recognized in amazon-corretto-11.0.16.9.1-linux-x64

### ISSUE THREAD

**Issue by cristianogiusti** [corretto/corretto-11#289]
### Describe the bug
I downloaded the file amazon-corretto-11.0.16.9.1-linux-x64.tar.gz from https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html site.

And It seems it doesn't support for Shenandoah GC because of the following:

[ec2-user@... bin]$ java -XX:+UseShenandoahGC --version
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### To Reproduce
Download the gz file. Unzip it in a folder and then run the command as described.

### Expected behavior
I expect Shenandoah GC is supported and in particular that the option 'UseShenandoahGC' is recognized.

### Platform information
    OS: Amazon Linux
    Version amazon-corretto-11.0.16.9.1-linux-x64

**Comment by lutkerd** [comment]
Can you share the output of `java -version` without the `-XX:+UseShenandoahGC` to make sure its running the correct java? I downloaded the tgz you mentioned and it is working for me.

```
$ ./amazon-corretto-11.0.16.9.1-linux-x64/bin/java -XX:+UseShenandoahGC -version
openjdk version "11.0.16.1" 2022-08-12 LTS
OpenJDK Runtime Environment Corretto-11.0.16.9.1 (build 11.0.16.1+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.16.9.1 (build 11.0.16.1+9-LTS, mixed mode)
```

**Comment by cristianogiusti** [comment]
Sorry, you are right, I was testing the wrong version. It is working for me as well.

Very appreciated your prompt reply.

Cheers
