### ISSUE TITLE
amazon-corretto-11.0.3.7.1-linux-x64.tar.gz contains duplicate file

### ISSUE THREAD

**Issue by tmssngr** [corretto/corretto-11#29]
### Describe the bug
The file amazon-corretto-11.0.3.7.1-linux-x64.tar.gz contains 2 amazon-corretto-11.0.3.7.1-linux-x64/lib/security/cacert files.

### To Reproduce
List all files contained in the amazon-corretto-11.0.3.7.1-linux-x64.tar.gz and grep for cacert.

### Expected behavior
A tar.gz file should only one file for one specific path.

### Platform information
    OS: any orderinary Linux

**Comment by jguo11** [comment]
Hi tmssngr@, I just checked the [`amazon-corretto-11.0.3.7.1-linux-x64.tar.gz`](https://d3pxv6yz143wms.cloudfront.net/11.0.3.7.1/amazon-corretto-11.0.3.7.1-linux-x64.tar.gz) downloaded from Corretto [download page](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html). But I only see one cacerts:

```
% ls -a amazon-corretto-11.0.3.7.1-linux-x64/lib/security | grep cacert
cacerts
```

**Comment by tmssngr** [comment]
Please try following command:
`$ tar -tvzf amazon-corretto-11.0.3.7.1-linux-x64.tar.gz | grep cacert`
and you should receive following output:
```
-rw-r--r-- 0/0          102883 2019-04-05 22:33 amazon-corretto-11.0.3.7.1-linux-x64/lib/security/cacerts
-rw-r--r-- 0/0          183421 2019-04-05 22:27 amazon-corretto-11.0.3.7.1-linux-x64/lib/security/cacerts  
```

**Comment by jguo11** [comment]
@tmssngr Thank you for the details. The `tar.gz` does include two cacerts and this is a bug. I re-examined the final cacerts after extraction and confirmed that cacerts is [the correct one](https://github.com/corretto/corretto-11/blob/develop/cacerts). In this case, it shouldn't affect the security level of Corretto11 `tar.gz`. 

We will get back to you soon once this is fixed.

**Comment by jguo11** [comment]
Starting from 11.0.4, we will include OpenJDK cacerts in Corretto cacerts.
