### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by sandbornm** [corretto/corretto-11#290]
### Describe the bug

Hello, I am getting an Exception Access Violation when running the [creoson server](https://github.com/SimplifiedLogic/creoson/blob/master/creoson-server/src/com/simplifiedlogic/nitro/jshell/MainServer.java) to automate the assembly of hundreds of designs in Creo Parametric 5.6.0.

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffeeadc9b6b, pid=5808, tid=5428
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.13.8.1 (11.0.13+8) (build 11.0.13+8-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.13.8.1 (11.0.13+8-LTS, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [pfcasyncmt.dll+0x1c9b6b]
#
# Core dump will be written. Default location: C:\CreosonServerWithSetup-2.8.0-win64\hs_err_pid5808.mdmp
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-11/issues/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

```

### To Reproduce

The command line args (from attached log file)
`-Dsli.jlink.timeout=200 -Dsli.socket.port=9056 com.simplifiedlogic.nitro.jshell.MainServer`

I have tried changing the jlink timeout to something like 9999, but the same error occurs. It looks like the crash may be indirectly related to the `pfcasyncmt.dll`. I have also posted about this issue [here](https://community.ptc.com/t5/Customization/EXCEPTION-ACCESS-VIOLATION-in-pfcasyncmt-dll-when-running/m-p/825982). I apologize if this is the wrong place or has been addressed before. 

Unfortunately, I do not have many details with respect to consistently reproducing the issue, but it _seems_ to be related to some kind of connection timeout. If it helps, the task of assembling each of the designs in Creo is done through Creoson via JSON requests. This is a single stage within a Jenkins Pipeline. The error in Jenkins console output when this crash happens is

```urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026E19566800>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it```

The creoson server is started from the command line from a .bat script with the following command:

`"%JAVA_HOME%\bin\java" -classpath "%cp%" -Dsli.jlink.timeout=9999 -Dsli.socket.port=%JSON_PORT% com.simplifiedlogic.nitro.jshell.MainServer`

and the environment variables are (see attached logs for more context): 

```
Environment Variables:
JAVA_HOME=C:\Program Files\Amazon Corretto\jdk11.0.13_8
USERNAME=Administrator
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
```
### Expected behavior

The server should not be crashing and has handled long-term runs successfully in this pipeline before

### Screenshots

![Screen Shot 2022-09-26 at 12 44 34 PM](https://user-images.githubusercontent.com/35283365/192344939-68f0dc3d-771f-4322-bce4-85fe11de5cc6.png)

### Platform information

From one of the VM error report crash log (a few are also attached): 
```

--------------- S Y S T E M ---------------

OS: Windows Server 2019 , 64 bit Build 17763 (10.0.17763.3287)
OS uptime: 2 days 5:29 hours
Xen hardware-assisted virtualization detected

CPU:total 4 (initial active 4) (4 cores per cpu, 1 threads per core) family 6 model 79 stepping 1 microcode 0xb000040, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, lzcnt, tsc, bmi1, bmi2, fma

Memory: 4k page, system-wide physical 16383M (10072M free)
TotalPageFile size 18815M (AvailPageFile size 12248M)
current process WorkingSet (physical memory assigned to process): 247M, peak: 272M
current process commit charge ("private bytes"): 368M, peak: 405M

vm_info: OpenJDK 64-Bit Server VM (11.0.13+8-LTS) for windows-amd64 JRE (11.0.13+8-LTS), built on Oct 13 2021 21:32:06 by "Administrator" with unknown MS VC++:1916
```

### Additional context

I apologize if this is the wrong place to post or if this issue is addressed adequately elsewhere. Thank you!

VM crash logs (can also provide .mdmp files if needed, I have not tried to examine the .mdmp files manually)
[hs_err_pid5584.log](https://github.com/corretto/corretto-11/files/9648467/hs_err_pid5584.log)
[hs_err_pid7292.log](https://github.com/corretto/corretto-11/files/9648468/hs_err_pid7292.log)
[hs_err_pid5808.log](https://github.com/corretto/corretto-11/files/9648487/hs_err_pid5808.log)

**Comment by benty-amzn** [comment]
Looking at the stack traces in the error logs, the crash is consistently happening in `pfcasyncmt.dll`, specifically the method `com.ptc.pfc.Implementation.pfcSession$Session.GetModelFromFileName(Ljava/lang/String;)Lcom/ptc/pfc/pfcModel/Model;`, so this is most likely not a Corretto bug.  I'd suggest following up on your post on the PTC forums or by opening an issue on their Github.

I do note that you're using Corretto 11.0.13, which is 3 releases out of date and missing several critical security patches. It's also possible the error would be resolved by updating to a newer release.

**Comment by sandbornm** [comment]
@benty-amzn Thank you!
