### ISSUE TITLE
Changelog has incorrect info for 11.0.18.11.1

### ISSUE THREAD

**Issue by ddillard** [corretto/corretto-11#311]
### Describe the bug
For each version in the changelog there is a table of CVEs that were fixed in that version.  In the section for 11.0.18.11.1 it appears there is a cut and paste error where some other number is in the CVSS field, the CVSS value is in the component field and the component value is not present.  For comparison just scroll down to the CVE table for version 11.0.17.8.1 where all the fields appear to be correct.

### To Reproduce
Look at the file.

### Expected behavior
I expected to see the proper values.

### Platform information
    OS: Any

### Additional context

For VM crashes, please attach the error report file. By default the file name is `hs_err_pidpid.log`, where pid is the process ID of the process.

**Comment by earthling-amzn** [comment]
Thank you for bringing this to our attention. We are looking into it.

**Comment by Rudometov** [comment]
The CVE sections have been updated.
