### ISSUE TITLE
Does generational mode to the Shenandoah GC GA?

### ISSUE THREAD

**Issue by cyberdak** [corretto/corretto-11#314]
### Is your feature request related to a problem?
ask for generational mode of shenandoahgc info.

### Describe a solution you would like
make sure state of  generational mode to the ShenandoahGC. it is still preview or GA?

**Comment by lutkerd** [comment]
Hi, sorry for the late response. Generational Shenandoah is not yet GA, but will also only be available on JDK17 and later, you can find the latest information in the [Readme](https://github.com/corretto/corretto-17/tree/generational-shenandoah#readme)
