### ISSUE TITLE
corretto-11 rpm packages does not provide libjvm.so rpm requires

### ISSUE THREAD

**Issue by thresheek** [corretto/corretto-11#315]
### Describe the bug
When building a RPM package depending on/using coretto-11 on Amazon Linux 2023, rpm-builds autodetects dependency on libjvm.so and adds it to a resulting rpm.  However, coretto-11 package (java-11-amazon-corretto-headless-11.0.18+10-1.amzn2023.x86_64) does not list it as provides.

### Additional context
It is already fixed in coretto-17 (via https://github.com/corretto/corretto-17/pull/108):

```
# rpm -q --provides java-17-amazon-corretto-headless-1:17.0.6+10-1.amzn2023.1.x86_64
config(java-17-amazon-corretto-headless) = 1:17.0.6+10-1.amzn2023.1
java-17-amazon-corretto-headless = 1:17.0.6+10-1.amzn2023.1
java-17-amazon-corretto-headless(x86-64) = 1:17.0.6+10-1.amzn2023.1
java-17-headless = 1:17.0.6+10-1.amzn2023.1
java-headless = 1:17.0.6
jre-17-amazon-corretto-headless = 1:17.0.6+10-1.amzn2023.1
jre-17-headless = 1:17.0.6+10-1.amzn2023.1
jre-headless = 1:17.0.6
libjava.so()(64bit)
libjsig.so()(64bit)
libjvm.so()(64bit)
libjvm.so(SUNWprivate_1.1)(64bit)
libverify.so()(64bit)
```

**Comment by lutkerd** [comment]
For AmazonLinux2023, Corretto-17 is the system JVM that provides libjvm. The library is unversioned and having multiple providers of it can cause some issues, there are some older [RHEL bugs ](https://bugzilla.redhat.com/show_bug.cgi?id=1702356.)about this issue.

Without knowing exactly what you are building there may need to be a [%__requires_excludes](https://docs.fedoraproject.org/en-US/packaging-guidelines/AutoProvidesAndRequiresFiltering/) directive added to the package. If there is a Java installed on the system, then the libjvm.so will be in the expected location.

**Comment by thresheek** [comment]
Thanks! `%__requires_excludes` is indeed an option since I can hardcode the dependency on an actual coretto distribution version via Requires instead (I explicitely add versioned BuildRequires in my java-related packages).
