### ISSUE TITLE
The tool jlink didn't preserve the signatures of files

### ISSUE THREAD

**Issue by gaoxingliang** [corretto/corretto-11#32]
### Describe the bug
the corretto jdk 11 jlink tool didn't preserve the digital signatures for java.exe and some other dll files on windows. but the oracle jlink tool is reserved.

### To Reproduce
Steps and (source) code to reproduce the behavior.
1. download amazon jdk 11, I'm using version 11.0.3.7.1.
2. run below jlink command to generate a new customized base runtime image:
`bin\jlink.exe --module-path jmods\ --output gen --add-modules java.base` 
3. open the output folder "gen" and check the new generated java.exe. the digital signatures are missing.

### Expected behavior
1. it should be same with oracle jlink and the digital signatures should be there.

### Screenshots
1. amazon jlink output file vs raw file:
![image](https://user-images.githubusercontent.com/3148215/59320321-77be7e00-8d00-11e9-86bf-efe83fed45cb.png)
2. oracle jlink output file:
![image](https://user-images.githubusercontent.com/3148215/59320355-a63c5900-8d00-11e9-9c3b-26648f55c0f2.png)

### Platform information
    OS: Windows
    Version:
openjdk 11.0.3 2019-04-16 LTS
OpenJDK Runtime Environment Corretto-11.0.3.7.1 (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.3.7.1 (build 11.0.3+7-LTS, mixed mode)

### Additional context
1. some dll files signatures are reserved, some are not. eg: jvm.dll is not reserved.

**Comment by yoroto** [comment]
Thank you for reporting it! We will look into it. 

Corretto is behaving the same as Zulu and RedHat JDKs here.

**Comment by gaoxingliang** [comment]
I wrote a class to re-sign those not signed files at - [SignJRE](https://github.com/gaoxingliang/jdk11TemplateProject/blob/master/src/java/SignJRE.java)
Hope it help

**Comment by yoroto** [comment]
The behavior of jlink in Corretto is consistent with all OpenJDK distributions. The idea is, if users would like to package and distribute a Java Runtime, it would be better to sign the binaries with their own key pairs rather than using the one from the original distribution.
