### ISSUE TITLE
cgroups v2 are not fully supported due to reliance on cpuacct controller

### ISSUE THREAD

**Issue by piax93** [corretto/corretto-11#320]
### Describe the bug

In migrating containerized Java workloads running on Corretto 11 to the latest Ubuntu LTS, we noticed issues in limiting memory allocation. Searching around led us to https://github.com/corretto/corretto-11/issues/228 which described the initial lack of support for cgroups v2, which should have been addressed in the July 2022 release. We ensured to be running a version more recent than that, but the issue persisted, which could be easily confirmed by running this small test (the detected memory is the whole physical allocation for the host, rather than the value set by docker cgroups):

```
$ docker run --rm -m 1GB amazoncorretto:11 java -XX:MaxRAMPercentage=80 -XshowSettings:vm -version
VM settings:
    Max. Heap Size (Estimated): 29.97G
    Using VM: OpenJDK 64-Bit Server VM

openjdk version "11.0.18" 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-11.0.18.10.1 (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.18.10.1 (build 11.0.18+10-LTS, mixed mode)
```

I digged a bit into the implementation of how cgroups are detected and loaded by the JVM, and I think I narrowed down the issue to these 2 sections:

https://github.com/corretto/corretto-11/blob/ad641b6b39c990ddc4f60cb318a17dcf5007647f/src/hotspot/os/linux/cgroupSubsystem_linux.cpp#L203-L207

https://github.com/corretto/corretto-11/blob/ad641b6b39c990ddc4f60cb318a17dcf5007647f/src/hotspot/os/linux/cgroupSubsystem_linux.cpp#L220-L223

[From documentation, the `cpuacct` controller is no longer present in the unified v2 hierarchy](https://manpages.ubuntu.com/manpages/jammy/man5/systemd.resource-control.5.html#unified%20and%20legacy%20control%20group%20hierarchies), which can be verified by looking at `/proc/cgroups` (hierarchy is != 0):

```
$ cat /proc/cgroups
#subsys_name    hierarchy       num_cgroups     enabled
cpuset  0       612     1
cpu     0       612     1
cpuacct 3       1       1
blkio   0       612     1
memory  0       612     1
...
```

This means that `determine_type` fails to recognize both cgroups v1 (because not mounted) and v2, leading to fall back reading memory limits directly from host resources (or at least this is the conclusion I was able to draw, correct me if I'm wrong).

### To Reproduce
On up to date Ubuntu 22.04 installation with `docker` installed, and systemd used as the cgroup driver
```
docker run --rm -m 1GB amazoncorretto:11 java -XX:MaxRAMPercentage=80 -XshowSettings:vm -version
```
reports wrong heap size values.

### Expected behavior
The above shows 800M of estimated heap size.

### Platform information
OS:  Ubuntu 22.04.2 LTS (Jammy Jellyfish)
Systemd: 
```
$ systemctl --version
systemd 249 (249.11-0ubuntu3.7)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```
Docker: 
```
$ docker version
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.3
 Git commit:        20.10.12-0ubuntu4
 Built:             Mon Mar  7 17:10:06 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.3
  Git commit:       20.10.12-0ubuntu4
  Built:            Mon Mar  7 15:57:50 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12-0ubuntu1~22.04.1
  GitCommit:
 runc:
  Version:          1.1.4-0ubuntu1~22.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Comment by piax93** [comment]
I was able to pretty much validate the assumption by applying this simple patch

```patch
diff --git a/src/hotspot/os/linux/cgroupSubsystem_linux.cpp b/src/hotspot/os/linux/cgroupSubsystem_linux.cpp
index 81e5e332b8..dd5c4434ee 100644
--- a/src/hotspot/os/linux/cgroupSubsystem_linux.cpp
+++ b/src/hotspot/os/linux/cgroupSubsystem_linux.cpp
@@ -218,7 +218,8 @@ bool CgroupSubsystemFactory::determine_type(CgroupInfo* cg_infos,
   for (int i = 0; i < CG_INFO_LENGTH; i++) {
     // pids controller is optional. All other controllers are required
     if (i != PIDS_IDX) {
-      is_cgroupsV2 = is_cgroupsV2 && cg_infos[i]._hierarchy_id == 0;
+      // cpuacct is replaced by cpu in cgroups v2
+      is_cgroupsV2 = is_cgroupsV2 && (cg_infos[i]._hierarchy_id == 0 || i == CPUACCT_IDX);
       all_required_controllers_enabled = all_required_controllers_enabled && cg_infos[i]._enabled;
     }
     if (log_is_enabled(Debug, os, container) && !cg_infos[i]._enabled) {
```

and the resulting binary can pick up the memory limits correctly

```
$ docker run -v $(realpath build):/src/build --rm -it --memory 1G ubuntu:jammy ./src/build/linux-x86_64-normal-server-release/jdk/bin/java -XX:MaxRAMPercentage=80 -XshowSettings:vm -version
VM settings:
    Max. Heap Size (Estimated): 792.69M
    Using VM: OpenJDK 64-Bit Server VM

openjdk version "11.0.19-internal" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.19-internal+0-adhoc..src, mixed mode)
```

**Comment by benty-amzn** [comment]
Hi, thank you for reporting this and the detailed reproduction instructions & patch. We're looking into this and will post an update when one is available.

**Comment by benty-amzn** [comment]
Is there any more information you can provide about how to reproduce the issue?

I have created an Ubuntu 22.04 ec2 instance,
- Ran `sudo apt update && sudo apt upgrade -y`
- Installed docker with `sudo apt install docker.io`
- Configured docker to use systemd as the cgroups controller by creating `/etc/docker/daemon.json` with contents
```
{
  "exec-opts": ["native.cgroupdriver=systemd"]
}
```

After this, I rebooted the instance, and performed the following checks:

```
ubuntu@ubuntu:~$ uname -a
Linux ubuntu 5.19.0-1022-aws #23~22.04.1-Ubuntu SMP Fri Mar 17 15:38:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```
ubuntu@ubuntu:~$ docker run --rm -m 1GB amazoncorretto:11 java -XX:MaxRAMPercentage=80 -XshowSettings:vm -version
VM settings:
    Max. Heap Size (Estimated): 792.69M
    Using VM: OpenJDK 64-Bit Server VM

openjdk version "11.0.18" 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-11.0.18.10.1 (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.18.10.1 (build 11.0.18+10-LTS, mixed mode)
```

```
ubuntu@ubuntu:~$ docker run --rm amazoncorretto:11 java -XX:MaxRAMPercentage=80 -XshowSettings:vm -version
VM settings:
    Max. Heap Size (Estimated): 12.14G
    Using VM: OpenJDK 64-Bit Server VM

openjdk version "11.0.18" 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-11.0.18.10.1 (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.18.10.1 (build 11.0.18+10-LTS, mixed mode)
```

It seems to me that the behavior is correct and I cannot reproduce the issue described. Are there any other settings in your usecase which may be impacting the results?

**Comment by piax93** [comment]
You are correct. Conducting further inspection on a different VM setup I was able to identify a tiny detail in our standard configuration management which causes the resulting cgroup configuration to appear as a sort of hybrid between v1 and v2, which of course ends up confusing the JVM implementation when it comes to loading resource limits. Apologies for the noise.
