### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by claudiodp84** [corretto/corretto-11#348]
### Describe the bug
A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffd84be55e4, pid=5452, tid=13564
#
# JRE version: OpenJDK Runtime Environment OpenLogic-OpenJDK (11.0.19+7) (build 11.0.19+7-adhoc..jdk11u)
# Java VM: OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (11.0.19+7-adhoc..jdk11u, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)

### Platform information
    OS: Windows Server 2019 OS Version 10
    Version: openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment OpenLogic-OpenJDK (build 11.0.19+7-adhoc..jdk11u)
OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 11.0.19+7-adhoc..jdk11u, mixed mode)
[hs_err_pid5452.log](https://github.com/corretto/corretto-11/files/12913762/hs_err_pid5452.log)

**Comment by davecurrie** [comment]
Hi, thanks for getting in touch.

Note that this crash is not happening with Corretto, it is happening in an OpenLogic build of OpenJDK.

Regardless of the JDK build, the crash is happening in native code outside the JVM (see lines 9 and 15 of the hs_err file you attached). It is not a JVM bug.

The DLL that causes the crash is called "libS3_1MD.dll", which I checked with our SDK team and is not provided by AWS. I recommend you discuss with the vendor who provides the software you're using.
