### ISSUE TITLE
questdb 7.2 run in  amd64/amazoncorretto:11-alpine3.18  container

### ISSUE THREAD

**Issue by ZhihuiJia** [corretto/corretto-11#353]
2023-12-04T03:11:41.954777Z I i.q.g.SqlCompiler plan [q=`select-choose ts, table_name, column_name, table_id, truncate_version, columnType, table_partition_by, updated_txn, column_version, partition_timestamp, partition_name_txn, completed from (select [ts, table_name, column_name, table_id, truncate_version, columnType, table_partition_by, updated_txn, column_version, partition_timestamp, partition_name_txn, completed] from sys.column_versions_purge_log timestamp (ts) where completed = null)`, fd=-1]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000000a466, pid=50, tid=54
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.21.9.1 (11.0.21+9) (build 11.0.21+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.21.9.1 (11.0.21+9-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  0x000000000000a466
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/questdb-no-jre-7.2/hs_err_pid50.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-11/issues/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted

**Comment by ZhihuiJia** [comment]
---------------  S U M M A R Y ------------

Command Line: --module-path=questdb.jar -Djdk.module.main=io.questdb io.questdb/io.questdb.ServerMain -d /opt/

Host: x86_64, 5 cores, 7G, Alpine Linux v3.18
Time: Mon Dec  4 03:11:42 2023 UTC elapsed time: 6.525881 seconds (0d 0h 0m 6s)

---------------  T H R E A D  ---------------

Current thread (0x000000400b5ab800):  JavaThread "main" [_thread_in_native, id=54, stack(0x0000004002bd7000,0x0000004002cd7ad8)]

Stack: [0x0000004002bd7000,0x0000004002cd7ad8],  sp=0x0000004002cd58c8,  free space=1018k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x000000000000a466

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  io.questdb.jit.FiltersCompiler.compileFunction(JJILio/questdb/jit/FiltersCompiler$JitError;)J+0 io.questdb@7.2
j  io.questdb.jit.CompiledFilter.compile(Lio/questdb/cairo/vm/api/MemoryCARW;I)V+39 io.questdb@7.2
j  io.questdb.griffin.SqlCodeGenerator.generateFilter0(Lio/questdb/cairo/sql/RecordCursorFactory;Lio/questdb/griffin/model/QueryModel;Lio/questdb/griffin/SqlExecutionContext;Lio/questdb/griffin/model/ExpressionNode;)Lio/questdb/cairo/sql/RecordCursorFactory;+383 io.questdb@7.2
j  io.questdb.griffin.SqlCodeGenerator.generateFilter(Lio/questdb/cairo/sql/RecordCursorFactory;Lio/questdb/griffin/model/QueryModel;Lio/questdb/griffin/SqlExecutionContext;)Lio/questdb/cairo/sql/RecordCursorFactory;+21 io.questdb@7.2
j  io.questdb.griffin.SqlCodeGenerator.generateQuery0(Lio/questdb/griffin/model/QueryModel;Lio/questdb/griffin/SqlExecutionContext;Z)Lio/questdb/cairo/sql/RecordCursorFactory;+13 io.questdb@7.2
j  io.questdb.griffin.SqlCodeGenerator.generateQuery(Lio/questdb/griffin/model/QueryModel;Lio/questdb/griffin/SqlExecutionContext;Z)Lio/questdb/cairo/sql/RecordCursorFactory;+4 io.questdb@7.2
j  io.questdb.griffin.SqlCodeGenerator.generateSubQuery(Lio/questdb/griffin/model/QueryModel;Lio/questdb/griffin/SqlExecutionContext;)Lio/questdb/cairo/sql/RecordCursorFactory;+28 io.questdb@7.2
j  io.questdb.griffin.SqlCodeGenerator.generateSelectChoose(Lio/questdb/griffin/model/QueryModel;Lio/questdb/griffin/SqlExecutionContext;)Lio/questdb/cairo/sql/RecordCursorFactory;+36 io.questdb@7.2
j  io.questdb.griffin.SqlCodeGenerator.generateSelect(Lio/questdb/griffin/model/QueryModel;Lio/questdb/griffin/SqlExecutionContext;Z)Lio/questdb/cairo/sql/RecordCursorFactory;+47 io.questdb@7.2
j  io.questdb.griffin.SqlCodeGenerator.generateQuery0(Lio/questdb/griffin/model/QueryModel;Lio/questdb/griffin/SqlExecutionContext;Z)Lio/questdb/cairo/sql/RecordCursorFactory;+8 io.questdb@7.2
j  io.questdb.griffin.SqlCodeGenerator.generateQuery(Lio/questdb/griffin/model/QueryModel;Lio/questdb/griffin/SqlExecutionContext;Z)Lio/questdb/cairo/sql/RecordCursorFactory;+4 io.questdb@7.2
j  io.questdb.griffin.SqlCodeGenerator.generate(Lio/questdb/griffin/model/QueryModel;Lio/questdb/griffin/SqlExecutionContext;)Lio/questdb/cairo/sql/RecordCursorFactory;+4 io.questdb@7.2
j  io.questdb.griffin.SqlCompiler.generate(Lio/questdb/griffin/model/QueryModel;Lio/questdb/griffin/SqlExecutionContext;)Lio/questdb/cairo/sql/RecordCursorFactory;+6 io.questdb@7.2
j  io.questdb.griffin.SqlCompiler.compileUsingModel(Lio/questdb/griffin/SqlExecutionContext;)Lio/questdb/griffin/CompiledQuery;+134 io.questdb@7.2
j  io.questdb.griffin.SqlCompiler.compileInner(Lio/questdb/griffin/SqlExecutionContext;Ljava/lang/CharSequence;)Lio/questdb/griffin/CompiledQuery;+83 io.questdb@7.2
j  io.questdb.griffin.SqlCompiler.compile(Ljava/lang/CharSequence;Lio/questdb/griffin/SqlExecutionContext;)Lio/questdb/griffin/CompiledQuery;+20 io.questdb@7.2
j  io.questdb.griffin.SqlCompiler$QueryBuilder.compile(Lio/questdb/griffin/SqlExecutionContext;)Lio/questdb/griffin/CompiledQuery;+9 io.questdb@7.2
j  io.questdb.cairo.ColumnPurgeJob.processTableRecords(Lio/questdb/cairo/CairoEngine;)V+33 io.questdb@7.2
j  io.questdb.cairo.ColumnPurgeJob.<init>(Lio/questdb/cairo/CairoEngine;Lio/questdb/griffin/FunctionFactoryCache;)V+257 io.questdb@7.2
j  io.questdb.cairo.O3Utils.setupWorkerPool(Lio/questdb/mp/WorkerPool;Lio/questdb/cairo/CairoEngine;Lio/questdb/cairo/sql/SqlExecutionCircuitBreakerConfiguration;Lio/questdb/griffin/FunctionFactoryCache;)V+51 io.questdb@7.2
j  io.questdb.ServerMain$1.configureSharedPool(Lio/questdb/mp/WorkerPool;)V+94 io.questdb@7.2
j  io.questdb.WorkerPoolManager.<init>(Lio/questdb/ServerConfiguration;Lio/questdb/metrics/HealthMetrics;)V+61 io.questdb@7.2
j  io.questdb.ServerMain$1.<init>(Lio/questdb/ServerMain;Lio/questdb/ServerConfiguration;Lio/questdb/metrics/HealthMetrics;ZLio/questdb/ServerConfiguration;Lio/questdb/griffin/FunctionFactoryCache;ZLio/questdb/griffin/DatabaseSnapshotAgent;ZLio/questdb/cairo/CairoConfiguration;)V+50 io.questdb@7.2
j  io.questdb.ServerMain.<init>(Lio/questdb/ServerConfiguration;Lio/questdb/Metrics;Lio/questdb/log/Log;Ljava/lang/String;)V+197 io.questdb@7.2
j  io.questdb.ServerMain.<init>(Lio/questdb/Bootstrap;)V+17 io.questdb@7.2
j  io.questdb.ServerMain.<init>([Ljava/lang/String;)V+9 io.questdb@7.2
j  io.questdb.ServerMain.main([Ljava/lang/String;)V+5 io.questdb@7.2
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x000000000000a466

Register to memory mapping:

RAX=0x0000004002cd5ea0 is pointing into the stack for thread: 0x000000400b5ab800
RBX=0x000000402d703589: <offset 0x000000000007b589> in /tmp/libquestdb9777541406584465029.so at 0x000000402d688000
RCX=0xffffffffffffffff is an unknown value
RDX=0x0000000000000001 is an unknown value
RSP=0x0000004002cd58c8 is pointing into the stack for thread: 0x000000400b5ab800
RBP=0x0000004002cd5d70 is pointing into the stack for thread: 0x000000400b5ab800
RSI=0x0000000000000107 is an unknown value
RDI=0x0000004002cd5d90 is pointing into the stack for thread: 0x000000400b5ab800
R8 =0x000000402d703589: <offset 0x000000000007b589> in /tmp/libquestdb9777541406584465029.so at 0x000000402d688000
R9 =0x0000004002cd5d58 is pointing into the stack for thread: 0x000000400b5ab800
R10=0x0000000000000008 is an unknown value
R11=0x0000000000000006 is an unknown value
R12=0x0000000000000020 is an unknown value
R13=0x0000000000000001 is an unknown value
R14=0x0 is NULL
R15=0x0000000000000107 is an unknown value


Registers:
RAX=0x0000004002cd5ea0, RBX=0x000000402d703589, RCX=0xffffffffffffffff, RDX=0x0000000000000001
RSP=0x0000004002cd58c8, RBP=0x0000004002cd5d70, RSI=0x0000000000000107, RDI=0x0000004002cd5d90
R8 =0x000000402d703589, R9 =0x0000004002cd5d58, R10=0x0000000000000008, R11=0x0000000000000006
R12=0x0000000000000020, R13=0x0000000000000001, R14=0x0000000000000000, R15=0x0000000000000107
RIP=0x000000000000a466, EFLAGS=0x0000000000000206, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
  TRAPNO=0xffffffffffffffff

Top of Stack: (sp=0x0000004002cd58c8)
0x0000004002cd58c8:   000000402d6ca643 0000000000000000
0x0000004002cd58d8:   0000003000000020 0000004002cd5f80
0x0000004002cd58e8:   0000004002cd5ea0 0000000000000000
0x0000004002cd58f8:   0000000000000000 0000004002cd5cc0 

Instructions: (pc=0x000000000000a466)
0x000000000000a366:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a376:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a386:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a396:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a3a6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a3b6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a3c6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a3d6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a3e6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a3f6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a406:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a416:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a426:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a436:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a446:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a456:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a466:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a476:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a486:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a496:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a4a6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a4b6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a4c6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a4d6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a4e6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a4f6:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a506:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a516:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a526:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a536:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a546:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
0x000000000000a556:   ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? 


Stack slot to memory mapping:
stack at sp + 0 slots: 0x000000402d6ca643: <offset 0x0000000000042643> in /tmp/libquestdb9777541406584465029.so at 0x000000402d688000
stack at sp + 1 slots: 0x0 is NULL
stack at sp + 2 slots: 0x0000003000000020 is an unknown value
stack at sp + 3 slots: 0x0000004002cd5f80 is pointing into the stack for thread: 0x000000400b5ab800
stack at sp + 4 slots: 0x0000004002cd5ea0 is pointing into the stack for thread: 0x000000400b5ab800
stack at sp + 5 slots: 0x0 is NULL
stack at sp + 6 slots: 0x0 is NULL
stack at sp + 7 slots: 0x0000004002cd5cc0 is pointing into the stack for thread: 0x000000400b5ab800


---------------  P R O C E S S  ---------------

Threads class SMR info:
_java_thread_list=0x000000403cda67b0, length=10, elements={
0x000000400b5ab800, 0x000000402b3f0800, 0x000000402b3f1800, 0x000000402b63e800,
0x000000402b63f800, 0x000000402b844800, 0x000000402b845800, 0x000000402b846800,
0x000000402b245800, 0x000000402eb33800
}

Java Threads: ( => current thread )
=>0x000000400b5ab800 JavaThread "main" [_thread_in_native, id=54, stack(0x0000004002bd7000,0x0000004002cd7ad8)]
  0x000000402b3f0800 JavaThread "Reference Handler" daemon [_thread_blocked, id=61, stack(0x000000402b3f4000,0x000000402b4f4ac0)]
  0x000000402b3f1800 JavaThread "Finalizer" daemon [_thread_blocked, id=62, stack(0x000000402b4fe000,0x000000402b5feac0)]
  0x000000402b63e800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=63, stack(0x000000402b640000,0x000000402b740ac0)]
  0x000000402b63f800 JavaThread "Service Thread" daemon [_thread_blocked, id=64, stack(0x000000402b741000,0x000000402b841ac0)]
  0x000000402b844800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=65, stack(0x000000402b848000,0x000000402b948ac0)]
  0x000000402b845800 JavaThread "C1 CompilerThread0" daemon [_thread_blocked, id=66, stack(0x000000402b949000,0x000000402ba49ac0)]
  0x000000402b846800 JavaThread "Sweeper thread" daemon [_thread_blocked, id=67, stack(0x000000402ba4a000,0x000000402bb4aac0)]
  0x000000402b245800 JavaThread "Common-Cleaner" daemon [_thread_blocked, id=68, stack(0x000000402bddf000,0x000000402bedfac0)]
  0x000000402eb33800 JavaThread "questdb-logging-1" daemon [_thread_blocked, id=71, stack(0x000000402eb39000,0x000000402ec39ac0)]

Other Threads:
  0x000000402b246800 VMThread "VM Thread" [stack: 0x000000402b2d6000,0x000000402b3d6ac0] [id=60]
  0x000000402d0c9000 WatcherThread [stack: 0x000000402d146000,0x000000402d246ac0] [id=70]
  0x0000004022fdb800 GCTaskThread "GC Thread#0" [stack: 0x0000004022fe4000,0x00000040230e4ac0] [id=55]
  0x000000402d0ca800 GCTaskThread "GC Thread#1" [stack: 0x0000004030556000,0x0000004030656ac0] [id=72]
  0x0000004027f44800 ConcurrentGCThread "G1 Main Marker" [stack: 0x0000004027f47000,0x0000004028047ac0] [id=56]
  0x0000004028048800 ConcurrentGCThread "G1 Conc#0" [stack: 0x000000402804b000,0x000000402814bac0] [id=57]
  0x000000402a6e5800 ConcurrentGCThread "G1 Refine#0" [stack: 0x000000402a6eb000,0x000000402a7ebac0] [id=58]
  0x000000402a6e6800 ConcurrentGCThread "G1 Young RemSet Sampling" [stack: 0x000000402a7ee000,0x000000402a8eeac0] [id=59]

Threads with active compile tasks:

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap address: 0x0000000085400000, size: 1964 MB, Compressed Oops mode: 32-bit
Narrow klass base: 0x0000000000000000, Narrow klass shi

**Comment by ZhihuiJia** [comment]
log info

**Comment by davecurrie** [comment]
Note that the error message says "The crash happened outside the Java Virtual Machine in native code." This looks like a crash in a QuestDB native library. I recommend opening the issue on their GitHub.
