### ISSUE TITLE
Add the ability to upgrade Corretto JDK 11 through command line

### ISSUE THREAD

**Issue by pavankjadda** [corretto/corretto-11#43]
### Is your feature request related to a problem?
Please add the ability to update the JDK through command line. It is painful to download, install the package and update the path for every new release

### Describe a solution you would like
Provide an alternate way to install and upgrade Corretto JDK either through HomeBrew, AWS SDK or NPM

**Comment by jguo11** [comment]
@pavankjadda Thank you for the request. Corretto11 is available in Homebrew and you can install it with `brew cask install corretto`. We are also actively working on distributing Corretto artifacts through other options such as yum and Debian repositories.

```
▶ brew cask info corretto
corretto: 11.0.4.11.1
https://aws.amazon.com/corretto/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/corretto.rb
==> Name
Amazon Corretto
==> Artifacts
amazon-corretto-11.0.4.11.1-macosx-x64.pkg (Pkg)
```
