### ISSUE TITLE
JRE packages are missed in Corretto11.

### ISSUE THREAD

**Issue by YogeshRajTR** [corretto/corretto-11#44]
Thank you for taking the time to help improve OpenJDK and Corretto 11.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your idea concerns OpenJDK 11
and is not specific to Corretto 11
we ask that you propose it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system](https://bugs.openjdk.java.net/) or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or [update project](http://mail.openjdk.java.net/mailman/listinfo/jdk-updates-dev)).

If your proposal is specific to Corretto 11,
then you are in the right place.
Please proceed with the following.

### Is your feature request related to a problem?
Please provide a clear and concise description of what the problem is.

### Describe a solution you would like
Please provide a clear and concise description of what you want to happen.

### Describe alternatives you have considered
Please provide a clear and concise description
of any alternative solutions or features you have considered.

**Comment by davecurrie** [comment]
Thanks for the feedback. OpenJDK 9 and later has removed the concept of a JRE. The suggested approach is to use jlink (https://openjdk.java.net/jeps/282) to build a custom package for your application. We don't discard building a pseudo-JRE for Corretto 11 in the future but it's not on the roadmap right now.
