### ISSUE TITLE
when will corretto 12 and 13 be available for use

### ISSUE THREAD

**Issue by srikaanthp** [corretto/corretto-11#47]

**Comment by cliveverghese** [comment]
Hi @srikaanthp,

We are currently focused on delivering LTS versions. However, this is open to change in the future. 
Are you looking to use these feature releases for testing or are you planning to deploy to production?

**Comment by srikaanthp** [comment]
I am planning to deploy these to production which is why i m curious about
the release dates

**Comment by disfluxly** [comment]
@cliveverghese  - How does the Corretto team determine if a specific release will be an LTS version? Or are you following the same pattern as the AdoptOpenJDK team?

> ...every three years one feature release will be designated as the Long Term Supported (LTS) release

**Comment by davecurrie** [comment]
@disfluxly We are using the same pattern as the rest of the community, which is as you say. The current LTS version is 11 and the next one is expected to be 17, in 2021.
