### ISSUE TITLE
incubator question

### ISSUE THREAD

**Issue by Z-torres** [corretto/corretto-11#49]
where is the jdk.incubator.*??

**Comment by davecurrie** [comment]
@Z-torres I assume you're trying to use `jdk.incubator.httpclient`, which shipped with JDKs 9 and 10. In JDK 11+, those have moved to `java.net.http` (see [JEP 321](https://openjdk.java.net/jeps/321) for more info.)

Please let us know if you are looking for a different package.

**Comment by Z-torres** [comment]
and jdk.incubator.vector?

**Comment by Z-torres** [comment]
> @Z-torres I assume you're trying to use `jdk.incubator.httpclient`, which shipped with JDKs 9 and 10. In JDK 11+, those have moved to `java.net.http` (see [JEP 321](https://openjdk.java.net/jeps/321) for more info.)
> 
> Please let us know if you are looking for a different package.

and jdk.incubator.vector

**Comment by davecurrie** [comment]
@Z-torres jdk.incubator.vector is part of [Project Panama](https://openjdk.java.net/projects/panama/) and not in OpenJDK 11 (or any OpenJDK version) yet.
