### ISSUE TITLE
Please backport JDK-8213202 : Possible race condition in TLS 1.3 session resumption

### ISSUE THREAD

**Issue by apara** [corretto/corretto-11#5]
We are looking to start using Java 11 in Production soon and would like to use Corretto, however, we are concerned about issue JDK-8213202 (https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8213202).  It appears to have been already fixed in Oracle's supported JVM 11.0.3.  Is there a plan to get this into Corretto soon?

Thanks.

**Comment by alvdavi** [comment]
Thanks for reaching out.

The bug you mention has been ported to the OpenJDK11 repository:
https://bugs.openjdk.java.net/browse/JDK-8218094

The change is scheduled for version 11.0.3, which is not yet out (either OpenJDK or Java). Once it is released, you will see Corretto releases with versions 11.0.3.x.x that most likely will contain the mentioned fix.

We will let you know if we decide to speed up the process and backport that patch into 11.0.2.x.x releases.
