### ISSUE TITLE
Wrong version inside package? | Problem with RSASSA-PSS

### ISSUE THREAD

**Issue by sha4ky** [corretto/corretto-11#54]
Hello,

On our project we try use Corretto11 with Jboss Eap 7.2, after migration we have face issues with 'ERR_SSL_PROTOCOL_ERROR' while trying access page by Chrome/Firefox browser (on IE11 works fine)

After analysing we have found there is a bug - https://bugs.openjdk.java.net/browse/JDK-8216039 , which should be already fixed, but we have found that latest version of Windows Corretto11 package on https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html with name "amazon-corretto-11.0.4.11.1-windows-x64.zip" indeed contains folder jdk11.0.4._10 (same for msi) while for Linux it's correct as 'amazon-correto-11.0.4.11.1-linux-x64'

Is that correct?

I'm asking because so far we are use workaround by adding ' RSASSA-PSS' to jdk.tls.disabledAlgorithms inside java.security file.

Maybe in newest version it's already fixed?

Big thanks in advance for any response.

**Comment by yoroto** [comment]
Hi @sha4ky 

Thank you for raising the issue!

The bug you mentioned here has been back ported in 11.0.5, which we would release very soon. Please check our next Corretto 11 release.

We will confirm the issue you raised about Windows installation folder.

**Comment by ziyiluo** [comment]
@sha4ky 

Corretto-11.0.5 has been released (download from [here](https://github.com/corretto/corretto-11/releases/tag/11.0.5.10.1)). Would you please verify the new version has fixed your issue?

**Comment by yamadamn** [comment]
@sha4ky Hi, I think you should use Red Hat OpenJDK (for Windows).
JBoss EAP 7 does not certify Amazon Corretto.[1]
If you use Red Hat OpenJDK, Red Hat will support this type of issue even in Windows.[2]

[1] https://access.redhat.com/articles/2026253
[2] https://access.redhat.com/articles/1299013

**Comment by sha4ky** [comment]
@ziyiluo Thanks for replay.

Unfortunately after updating to Corretto-11.0.5 we have another issue on server start:

`Encryption raised an exception. A possible cause is you are using strong encryption algorithms and you have not installed the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files in this Java Virtual Machine; nested exception is org.jasypt.exceptions.EncryptionOperationNotPossibleException: Encryption raised an exception. A possible cause is you are using strong encryption algorithms and you have not installed the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files in this Java Virtual Machine
	at org.wildfly.extension.undertow@7.2.0.GA-redhat-00005//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads@2.3.2.Final-redhat-1//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)`

JCE supposed to be embedded right? I have check also this flag crypto.policy inside java.security and change it to limited, but won't help at all.

**Comment by ziyiluo** [comment]
@sha4ky this is not caused by Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy as it has been enabled by default in all new JDK update versions. As [this](https://stackoverflow.com/questions/15544266/org-jasypt-exceptions-encryptionoperationnotpossibleexception/25010625) StackOverflow question mentioned, EncryptionOperationNotPossibleException is a general exception thrown by jasypt to mask other possible exceptions. So it may take a while for us to investigate. Besides, would you be able to provide a full stack trace, log that can help our investigation? Would you please describe your steps to reproduce the issue? Does JBoss EAP 7 run properly with other (Open)JDK11 distributions?

**Comment by davecurrie** [comment]
@sha4ky Do you have an update on this issue?
