### ISSUE TITLE
JRE load error

### ISSUE THREAD

**Issue by groundswel** [corretto/corretto-11#57]
bash-3.2$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home

Downloaded and tried to run pwsafe application and got a JRELoad error. 

http://jpwsafe.sourceforge.net

System: macOS Mojave 10.14.6

**Comment by navyxliu** [comment]
I can run it with corretto-11 on macOS Mojave 10.14.6.
What kind of error message do you have? could you also print out "java --version"

**Comment by groundswel** [comment]
bash-3.2$ java --version
openjdk 11.0.5 2019-10-15 LTS
OpenJDK Runtime Environment Corretto-11.0.5.10.1 (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.5.10.1 (build 11.0.5+10-LTS, mixed mode)

**Comment by groundswel** [comment]
The only error message I get is the UI fail to start and says JRE Load error

**Comment by ziyiluo** [comment]
The launcher of jpwsafe expects Java runtime environment (JRE) in the Internet plugin directory (i.e., `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home`). If the JRE is not found, the JRE Load error is raised. The Internet plugin directory is not where JDKs are installed on Mac. You can find the Java home of the installed JDK by running `/usr/libexec/java_home` in terminal. One workaround is to create a symlink `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home` -> `<the java_home of the installed JDK>`. In my local test, jpwsafe runs with both Corretto 8 and 11.

**Comment by groundswel** [comment]
bash-3.2$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home

.. so I think in my case I don't need to make any changes?

**Comment by groundswel** [comment]
Thank You!! That worked. Are there any plans to get a Mac Internet plugin for Corretto so that there is no need to do this hack.
