### ISSUE TITLE
 Corretto And Web-Start

### ISSUE THREAD

**Issue by kaiw1ng** [corretto/corretto-11#59]
Are there any plans of adding the Java web-start browser plug-in into Corretto?

Is this something the customer can request?

If not, does Amazon have any recommendations or guidelines for this? I have noticed some people online who have leveraged IcedTea with Corretto, but it would be more ideal if we could avoid additional layers.

thanks!

**Comment by davecurrie** [comment]
Hi @kaiw1ng 

We are tracking this in https://github.com/corretto/corretto-8/issues/5. The short answer is that we don't currently have plans to develop web start functionality but feel free to thumbs-up that issue and chime in with your use case. We have heard from people successfully using icedtea-web, as you mention.
