### ISSUE TITLE
Please backport JDK-8215396: JTabbedPane preferred size calculation is wrong for SCROLL_TAB_LAYOUT

### ISSUE THREAD

**Issue by mperktold** [corretto/corretto-11#63]
We would like to use JDK 11 in production, but we think that [JDK-8215396](https://bugs.openjdk.java.net/browse/JDK-8215396) might disturb our users. The problem was fixed in JDK 13 but not backported, therefore please backport it to JDK 11.

Appologies if this is the wrong place to open such a request.
I tried requesting this at https://bugs.java.com/bugdatabase/, but I didn't get any reaction so far, so I'm trying it here.
Also, if you can point me to a better place for requesting backports, please do so.

**Comment by cliveverghese** [comment]
Response to 

Hi @mperktold,

Thank you for your feedback. 
We have evaluated the bug you mentioned and it seems that the patch applies cleanly to JDK11. We will work on backporting this to Corretto and OpenJDK11.

While we are working on backporting this issue, can you tell us about your use case and the failure you are seeing? Are you currently using the workaround mentioned in the [JBS Bug](https://bugs.openjdk.java.net/browse/JDK-8215396)?

**Comment by mperktold** [comment]
Thanks @cliveverghese,

We didn't find a satisfactory workaround.

As for the problem itself, please see the following two screenshots showing the JFrames produced by the program provided in the original bug:

SCROLL_TAB_LAYOUT:
![grafik](https://user-images.githubusercontent.com/7334069/70703539-a548ac00-1cd0-11ea-9157-e1a6f3c393c2.png)

WRAP_TAB_LAYOUT:
![grafik](https://user-images.githubusercontent.com/7334069/70703571-aed21400-1cd0-11ea-98d0-03b8f3ca9b18.png)

They should look identical, but the one using SCROLL_TAB_LAYOUT is too small.

In our real app this causes some layout problems.

For instance, when data forms are embedded in a JTabbedPane using SCROLL_TAB_LAYOUT, the last row is too small.
See the following example of three stacked text fields:
![grafik](https://user-images.githubusercontent.com/7334069/70704332-163c9380-1cd2-11ea-98c6-af99716b4233.png)

Of course, the actual behavior depends on the LayoutManager used for the tab content, but the root of the problem is the wrong calculation of minimum and preferred size.

**Comment by mperktold** [comment]
Thanks!

Although I am pretty confident this will work as expected, could you please tell me how I can get a snapshot build of Corretto 11 in order to test this?

**Comment by davecurrie** [comment]
@mperktold We don't yet have snapshot builds of Corretto but you should be able to clone the repo to build and verify.

**Comment by mperktold** [comment]
I wasn't able to build a snapshot myself, but in the meantime, 11.0.6 was released, and I could verify the backport works. 👍
