### ISSUE TITLE
Will there be Corretto 11 32-bit windows builds available when it is GA?

### ISSUE THREAD

**Issue by annatindall** [corretto/corretto-11#7]
Additionally, is releasing a separate JRE alongside the JDK (as is the case with Corretto 8) planned?

Thanks!

**Comment by alvdavi** [comment]
Thanks for reaching @annatindall.

Currently, we have no plans on releasing a 32 bit build for Corretto11. We will continue providing support for the Corretto8 version.

Regarding the JRE, we are currently considering what would be the best way to provide it, should we decide so. There is no longer the concept of a JRE in OpenJDK11, It would have to be a tailored version of Corretto11 with only some of the modules to save space, but which modules to include ends up being a trade-off between size and compatibility.

Finally, the jlink tool is included in Corretto11, and it can be used to create a custom JRE if needed. This version will most likely be smaller than any we create.

David
