### ISSUE TITLE
Console access to allow mismatched certificates

### ISSUE THREAD

**Issue by htrumbu11** [corretto/corretto-11#72]
There are many situations where JAVA launches an HTTPS web page and that is using a certificate for a device with a certain IP or URL that is not mached to the IP or URL being used by the launcher. (Cisco ASDM, Eaton IPM, various VMware products etc) and to get around this you go into the JAVA console, create an exception for the certificate and then allow it to launch normally. Corretto does not seem to have any function to support this. Can this be added? Even it was a config file that has to be added to the root folder to populate the IP or URL would be a valid work around. Thanks,

**Comment by yoroto** [comment]
Hi @htrumbu11

Thank you for reporting the issue! It is a consistent behavior across OpenJDK distributions to not having such a security bypass. Please also refer to the similar issue in Corretto 8. https://github.com/corretto/corretto-8/issues/142
