### ISSUE TITLE
Can we use parameter 'MaxRAM' to set the max JVM memory in corretto-11?

### ISSUE THREAD

**Issue by jack-hewu** [corretto/corretto-11#76]

**Comment by AzeemJiva** [comment]
Hi @jack-hewu 
  The MaxRAM parameter is available in the latest Corretto 11

> ➜  ~ java -XX:MaxRAM=5000M -version
> openjdk version "11.0.6" 2020-01-14 LTS
> OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
> OpenJDK 64-Bit Server VM Corretto-11.0.6.10.1 (build 11.0.6+10-LTS, mixed mode)
> ➜  ~ java -XX:MaxRAM=5G -version
> openjdk version "11.0.6" 2020-01-14 LTS
> OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
> OpenJDK 64-Bit Server VM Corretto-11.0.6.10.1 (build 11.0.6+10-LTS, mixed mode)

**Comment by cliveverghese** [comment]
@jack-hewu, 

Did this approach work for you?

Please reopen if this did not solve your problem.
