### ISSUE TITLE
jlink fails with 'Invalid JMOD file' on macOS 10.15.2

### ISSUE THREAD

**Issue by brownms** [corretto/corretto-11#77]
### Describe the bug
Unable to run jlink to create a modular JRE using the latest release 11.0.6.10.1-1 for macOS. 

`Error: java.io.IOException: Invalid JMOD file: [redacted]/amazon-corretto-11.jdk/Contents/Home/jmods/jdk.jartool.jmod`

### To Reproduce
1. Download the [11.0.6.10.1-1 build of Corretto JDK for macOS](https://corretto.aws/downloads/resources/11.0.6.10.1/amazon-corretto-11.0.6.10.1-1-macosx-x64.tar.gz)
2. `tar xzf amazon-corretto-11.0.6.10.1-1-macosx-x64.tar.gz`
3. `cd amazon-corretto-11.jdk/Contents/Home/bin`
4. `./jlink --no-header-files --no-man-pages --compress=2 --strip-debug --add-modules java.datatransfer,java.desktop,java.instrument,java.logging,java.management,java.naming,java.prefs,java.scripting,java.security.jgss,java.sql,java.xml,java.xml.crypto --output my-jre`

### Expected behavior
JRE should be created in directory `amazon-corretto-11.jdk/Contents/Home/bin/my-jre`

### Platform information
    OS: macOS 10.15.2 (Also reproduced on macOS 10.13.6)
    Version:
        openjdk 11.0.6 2020-01-14 LTS
        OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
        OpenJDK 64-Bit Server VM Corretto-11.0.6.10.1 (build 11.0.6+10-LTS, mixed mode)

### Additional context
This appears to affect only macOS. Creating a JRE with Windows and Linux works as expected.

**Comment by ziyiluo** [comment]
@brownms We were aware of this issue. A release to fix the broken jmod files in macOS build is scheduled today. We will update this issue when the release is out.

**Comment by brownms** [comment]
@ziyiluo Thanks for the update.

**Comment by ziyiluo** [comment]
@brownms The release is out. Please download the latest mac artifacts from our [release page](https://github.com/corretto/corretto-11/releases/tag/11.0.6.10.1-2) to verify that it addresses the issue.

**Comment by brownms** [comment]
@ziyiluo Confirmed latest mac artifact fixes the problem. `jlink` works as expected.  Thanks!
