### ISSUE TITLE
Change in behaviour of java.util.TimeZone

### ISSUE THREAD

**Issue by divanmostert** [corretto/corretto-11#85]
### Describe the bug
TimeZone.getDefault() returns different results between 11.0.3 and 11.0.6. I am on a Mac, so not sure if other OS's are also affected.

### To Reproduce

Run the following code:
...
       TimeZone timeZone = TimeZone.getDefault();
       System.out.println(timeZone);
...

### Screenshots

**Running with 11.0.3 and earlier(e.g Java 8):**
sun.util.calendar.ZoneInfo[id="Africa/Windhoek",offset=7200000,dstSavings=0,useDaylight=false,transitions=54,lastRule=null]

**Running with 11.0.6:**
sun.util.calendar.ZoneInfo[id="Africa/Windhoek",offset=3600000,dstSavings=0,useDaylight=false,transitions=54,lastRule=null]

### Platform information
    OS: Mac OSX - 10.14.6 
    Version: 11.0.6+10-LTS

**Comment by pswargam** [comment]
Hi @divanmostert ,

Thank you for reporting this issue. We will investigate and get back to you. 

Thanks,
Prashanth

**Comment by pswargam** [comment]
Hi @divanmostert ,

System.out.println(timezone) will print some of the internal values on the underlying instance (in this case sun.util.calendar.ZoneInfo), but it will not include all the internal fields that are use to do a date calculation. We have been doing some testing and both versions will print the correct date, assuming an offset of two hours for Africa/Windhoek. 

The difference you are seeing comes from JDK-8212970, where how the internal representation of timezones changed, from using the rearguard formatting to use the vanguard formatting of the timezone database. This causes ZoneInfo fields like offset to now have different values ([compensated on the values of transitions, a fields that is not displayed when printing the timezone](http://hg.openjdk.java.net/jdk-updates/jdk11u/file/571c180c5106/src/java.base/share/classes/sun/util/calendar/ZoneInfo.java#l131)).

In any case, java.util.TimeZone is part of the specification, but sun.util.calendar.ZoneInfo is not, which means its internal behavior is subject to change. For that reason, usage of methods like toString on TimeZone is discouraged (as it will call http://hg.openjdk.java.net/jdk-updates/jdk11u/file/571c180c5106/src/java.base/share/classes/sun/util/calendar/ZoneInfo.java#l546)


Additionally, please consider using the newer java.time api with java.time.ZoneId and java.time.ZonedDateTime. 

Thanks,
Prashanth

**Comment by davecurrie** [comment]
Doesn't look like a bug, closing this issue.

**Comment by divanmostert** [comment]
Ok, guys,

I revisited this after many moons and tracked down where I think the problem is. It is with the SimpleDateFormat class which I used for string representation.

Running the below code will result in the time also being showed as updated when in fact it was not:

   `
    public static void main(String[] args) {
        testToString(2099);
        testToString(2020);
    }

    public static void testToString(int year) {
        Calendar c = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
        c.set(Calendar.YEAR, 2000);
        c.set(Calendar.MONTH, 11);
        c.set(Calendar.DAY_OF_MONTH, 31);
        c.set(Calendar.HOUR, 0);
        c.set(Calendar.MINUTE, 0);
        c.set(Calendar.SECOND, 0);
        c.set(Calendar.AM_PM, 1);

        java.util.Date gDate = c.getTime();

        DateFormat formatter = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG);
        formatter.setTimeZone(TimeZone.getTimeZone("GMT"));
        ((SimpleDateFormat) formatter).applyPattern("MMMMMM dd, yyyy HH:mm:ss a z");

        Calendar gregorianCalendar = new GregorianCalendar();

        gregorianCalendar.setTimeInMillis(gDate.getTime());
        gregorianCalendar.set(Calendar.YEAR, year);
        System.out.println(formatter.format(gregorianCalendar.getTime()) + "("+ gregorianCalendar.getTime()+")");
    }
`

Result is:

December 31, 2099 13:00:00 PM GMT(Thu Dec 31 14:00:00 CAT 2099)
December 31, 2020 12:00:00 PM GMT(Thu Dec 31 14:00:00 CAST 2020
