### ISSUE TITLE
SSL handshake error with 11.0.6.10.1-1 Windows JDK

### ISSUE THREAD

**Issue by gkersting** [corretto/corretto-11#88]
###  Describe the bug
When using Windows x64 11.0.6.10.1-1 Windows x64 JDK version, we are using JLink to create a JRE to deploy. When launching using the JRE we see the following error.
javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)...Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:102) at java.base/sun.security.validator.Validator.getInstance(Validator.java:181) at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:300)

When looking at the cacerts under /lib/security it is now around 157KB where before version 11.0.6.10.1 it was around 254kb

### To Reproduce
Use JLink to produce a JRE.  and use that JRE to launch an application that uses SSL.

### Expected behavior
Use JLink to produce a JRE that when used to run does not cause an SSL exception.
SSL handshake should work with delivered cacerts truststore.

### Workaround
Copy the CACERT file from the JDK into the directory created for the JRE that was created.

### Platform information
Microsoft Windows [Version 10.0.18362.592]
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
I installed the 11.0.6.10.1-1 version but it does not look like the version changed.

**Comment by davecurrie** [comment]
@gkersting Thanks. We're looking at it and will update here soon.

**Comment by javapapo** [comment]
I have the same problem on MacOSX by the way  - just for reference.

```bash
column 10: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

Correto:

```bash
❯ java -version
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.6.10.1 (build 11.0.6+10-LTS, mixed mode)
````

OS:
```❯ sw_vers
\ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287
```

**Comment by gkersting** [comment]
@ziyiluo Has this been released in a build yet? I notice there was a new build available for download.

**Comment by davecurrie** [comment]
@gkersting Corretto 11.0.7 fixes this. Please let us know if you keep having issues.
