### ISSUE TITLE
Supporting Corretto 11 on Windows Server 2019

### ISSUE THREAD

**Issue by ottfoekst** [corretto/corretto-11#89]
Are there any plans to support Corretto 11 on Windows Server 2019 in near future?

I know that Corretto 8 is already supported.
https://github.com/corretto/corretto-8/issues/206

**Comment by TianminShi** [comment]
Windows Server 2019 is already support since version 11.0.3. please let us know what makes you think it is not supported. so we can improve.

https://github.com/corretto/corretto-11/commit/9fb45a9b261cb9ca6dac1d9560c50ad17c715472#diff-37f78dd96ca6f9824354844a183d7633R1694

**Comment by ottfoekst** [comment]
Thank you for your reply.

Corretto 11 doesn't support Windows Server 2019 on the following page.
(Q: What operating systems does Corretto 11 support?)

https://aws.amazon.com/corretto/faqs/

**Comment by TianminShi** [comment]
the document has been updated 
https://aws.amazon.com/corretto/faqs/

**Comment by ottfoekst** [comment]
Please update document not only Corretto 8 but also Corretto 11.
