### ISSUE TITLE
How to track new releases?

### ISSUE THREAD

**Issue by mouse256** [corretto/corretto-11#9]
Question is what is the recommended way to track/get notified of new releases?
Current latest version is 11.0.2.9.2 (cfr https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/change-log.html)
But 2 places I could find to automatically get updated of new releases are not updated:
* release note rss feed: https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/corretto-11-ug.rss
* github releases page.

Can you provide pointers what is the best approach? I don't want to monitor the releases page manually.

**Comment by davecurrie** [comment]
@mouse256 Thanks, good points. You'll notice the Corretto 8 updates RSS is updated with new releases, so there was an oversight in why we didn't do that for the last release of 11. You should be able to track releases using that RSS. We'll look into why and fix it for upcoming releases.

GitHub releases are more complicated. We currently make Corretto binaries available using AWS services. If we decide to change that, we'll certainly look into this mechanism as a possible alternative.

**Comment by davecurrie** [comment]
Closing the issue. Corretto 11 updates are showing in the Corretto 11 RSS feed at https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/corretto-11-ug.rss
