### ISSUE TITLE
Request to prepend ubuntu and debian directories to Apt archive at apt.corretto.aws

### ISSUE THREAD

**Issue by smstone** [corretto/corretto-11#92]
### Is your feature request related to a problem?
Yes, when attempting to mirror `apt.corretto.aws` with `debmirror` [1], requests fail as the Corretto archive is not prepended with `ubuntu` or `debian` directories. Furthermore, `debmirror` currently does not support an empty archive root option [2], which is currently how `apt.corretto.aws` is setup without a root directory.

Per `debmirror` manpage in Ubuntu: 
```
-r, --root=directory
           Specifies the directory on the remote host that is the root of the Ubuntu archive. Defaults to ubuntu, which will work for most mirrors. The root directory has a dists subdirectory.
```
And the directory is `debian` for Debian.

### Describe a solution you would like
This request is to add a root directory of `ubuntu` and `debian` to `apt.corretto.aws` to allow the `debmirror` tool to sync, as it currently does not support empty roots per this bug report [2].

Example error output of `debmirror` run:

```
$ debmirror --verbose --debug --no-check-gpg --rsync-extra=none --host=apt.corretto.aws --method=http --dist=stable --section=main --arch=amd64 --nosource  --getcontents  --diff=none  --timeout=100  --nocleanup  /var/corretto 

< -- SNIP --> 
http://apt.corretto.aws/ubuntu/dists/stable/Release => [  0%] Getting: ubuntu/dists/stable/Release... 403 Forbidden
failed 403 Forbidden
Errors:
 Download of ubuntu/dists/stable/Release failed: 403 Forbidden
Failed to download some Release or Release.gpg files!
```
[1] https://manpages.debian.org/testing/debmirror/debmirror.1.en.html
[2] https://bugs.launchpad.net/ubuntu/+source/debmirror/+bug/1702059

Thank you for your consideration.

**Comment by pswargam** [comment]
Hi @smstone ,

Thank you for this feature request, We acknowledge and are looking into it. 

Thanks,
Prashanth

**Comment by davecurrie** [comment]
@smstone We have made a change in the repo structure, can you please check if it works for you now? The command you pasted works for us now in Debian and Ubuntu.

**Comment by smstone** [comment]
@davecurrie Yes, the command works for us now. Thank you!
