### ISSUE TITLE
Corretto JRE 11 doesn't seem to run on Server 2008

### ISSUE THREAD

**Issue by boochkn** [corretto/corretto-11#94]
### Describe the bug
running JAVA.exe on Server 2008 results in error: "The procedure entry point K32GetModuleFileNameExA could not be located in the dynamic link library KERNEL32.dll."

### To Reproduce
on a patched build of Server 2008, run java.exe -version

### Expected behavior
Java should run as normal

### Screenshots
![image](https://user-images.githubusercontent.com/26234536/78823192-43f8c700-79aa-11ea-8128-3ce7be41c9d4.png)

### Platform information
    OS: Windows Server 2008 Datacenter, version 6.0 (build 6003: Service Pack 2)
    Version 11.0.6.10.1

**Comment by boochkn** [comment]
I am able to use Corretto JRE8 both 32-bit and 64-bit on that same server without error.

**Comment by davecurrie** [comment]
Hi.

Corretto 11 is supported on Windows Server 2012 and above. Server 2008 is listed as supported but that is a mistake, thanks for finding it. I'll get that changed.

**Comment by boochkn** [comment]
Ok!  That makes sense...thanks for the fast response!

Matthew Cole
