### ISSUE TITLE
Please quit breaking symantic versioning

### ISSUE THREAD

**Issue by WardsParadox** [corretto/corretto-11#97]
Thank you for taking the time to help improve OpenJDK and Corretto 11.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 11
and is not specific to Corretto 11
we ask that you raise it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system](https://bugs.openjdk.java.net/) or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or [update project](http://mail.openjdk.java.net/mailman/listinfo/jdk-updates-dev).

If your issue is specific to Corretto 11,
then you are in the right place.
Please proceed with the following.

### Describe the bug
The Corretto team has released several updates in the past with -1 at the end of the release number. This breaks most auto patch loading software (such as [AutoPkg](https://github.com/autopkg/autopkg/))

### To Reproduce
Use any release using a -1 tag.

### Expected behavior
If it's a new item, it should be using a dot release form OR better yet, a higher build number.

### Platform information
    OS: [e.g. Amazon Linux 2]
    Version [e.g. "11.0.1+13-1" (output from "java -version")]

### Additional context
This really breaks anyone who's trying to do industry standard versioning patching automated.

**Comment by pswargam** [comment]
Hi @WardsParadox ,

Thank you for the feedback. ‘-1’ at the end represent repackagaing. We will bump the build number only if we rebuild the package. We will revisit ‘-1’ naming scheme for repackaging.

Thanks,
Prashanth
